GameConfig.cnfSkillInfo=
 {
  [1001]={
    skillName=[[普通攻击]],
    type=[[主动技能]],
    cdTime=[[1秒]],
    distance=[[近身攻击]],
    describe=[[普通攻击]],
    describe2=[[基本技能，挥动时剑气激射而出，释放一道剑气直击目标，命中目标后会对目标造成一定伤害，是每一个侠客行走江湖的基本技能！]],
    level={
      [1]={
          limitLevel=1,
          goldCoin=0,
          costBlue=0,
      },
    },
  },
  [3]={
    skillName=[[鏖战心法]],
    type=[[被动技能]],
    cdTime=[[0秒]],
    distance=nil,
    describe=[[战士的入门心法，随技能等级提升便能发挥出更多的有效伤害]],
    level={
      [1]={
          limitLevel=5,
          goldCoin=1,
          costBlue=0,
      },
      [2]={
          limitLevel=5,
          goldCoin=1,
          costBlue=0,
      },
      [3]={
          limitLevel=17,
          goldCoin=2,
          costBlue=0,
      },
      [4]={
          limitLevel=30,
          goldCoin=3,
          costBlue=0,
      },
    },
  },
  [7]={
    skillName=[[会心一击]],
    type=[[主动技能]],
    cdTime=[[0.75秒]],
    distance=nil,
    describe=[[战士剑术，有一定几率触发倍率攻击]],
    describe2=[[战士<COLOR VALUE=FF00FF7F>单体强攻</COLOR>技能，有一定几率触发倍率攻击，攻击时开启该技能有几率打出战士的最高攻击，对目标一击毙命！技能等级越高，触发倍率攻击的概率就会越大！]],
    level={
      [1]={
          limitLevel=26,
          goldCoin=100,
          costBlue=0,
      },
      [2]={
          limitLevel=26,
          goldCoin=100,
          costBlue=0,
      },
      [3]={
          limitLevel=38,
          goldCoin=200,
          costBlue=0,
      },
      [4]={
          limitLevel=51,
          goldCoin=500,
          costBlue=0,
      },
    },
  },
  [12]={
    skillName=[[两仪刀法]],
    type=[[主动技能]],
    cdTime=[[0.75秒]],
    distance=[[近身攻击]],
    describe=[[战士PK对决中最实用的刀法，使用时发出阴阳两道刀光，同时对前方2个目标造成伤害]],
    describe2=[[战士<COLOR VALUE=FF00FF7F>单体攻击</COLOR>技能，由唐朝第一杀手总结多年经验结合会心一击所创，对前方2个目标造成剧烈伤害<COLOR VALUE=FF00FF7F>破防御</COLOR>，<COLOR VALUE=FF00FF7F>破闪避</COLOR>！]],
    level={
      [1]={
          limitLevel=2,
          goldCoin=1,
          costBlue=0,
      },
      [2]={
          limitLevel=2,
          goldCoin=1,
          costBlue=0,
      },
      [3]={
          limitLevel=3,
          goldCoin=2,
          costBlue=0,
      },
      [4]={
          limitLevel=5,
          goldCoin=3,
          costBlue=0,
      },
    },
  },
  [25]={
    skillName=[[刀震八方]],
    type=[[主动技能]],
    cdTime=[[0.75秒]],
    distance=[[近身攻击]],
    describe=[[将刀气凝聚在武器上，挥动中对自身周围目标造成伤害]],
    describe2=[[战士<COLOR VALUE=FF00FF7F>群体攻击</COLOR>技能，吸取绝世武功秘籍上的精华所创，能将劲气凝聚在武器上同时对目标周围的<COLOR VALUE=FF00FF7F>8</COLOR>个敌人造成伤害，<COLOR VALUE=FF00FF7F>破防御</COLOR>，<COLOR VALUE=FF00FF7F>破闪避</COLOR>!]],
    level={
      [1]={
          limitLevel=16,
          goldCoin=200,
          costBlue=30,
      },
      [2]={
          limitLevel=16,
          goldCoin=200,
          costBlue=30,
      },
      [3]={
          limitLevel=28,
          goldCoin=400,
          costBlue=30,
      },
      [4]={
          limitLevel=41,
          goldCoin=1000,
          costBlue=30,
      },
    },
  },
  [26]={
    skillName=[[烈焰刀]],
    type=[[主动技能]],
    cdTime=[[10秒]],
    distance=[[近身攻击]],
    describe=[[附加火焰系伤害的强力一击，需要10秒的技能冷却时间]],
    describe2=[[战士<COLOR VALUE=FF00FF7F>单体攻击</COLOR>技能，使用时附加火焰系伤害，对当前目标造成致命一击，有极强的破坏力，但每次使用后，需要<COLOR VALUE=FF00FF7F>10</COLOR>秒的冷却时间！]],
    level={
      [1]={
          limitLevel=37,
          goldCoin=100,
          costBlue=70,
      },
      [2]={
          limitLevel=37,
          goldCoin=100,
          costBlue=70,
      },
      [3]={
          limitLevel=49,
          goldCoin=200,
          costBlue=70,
      },
      [4]={
          limitLevel=62,
          goldCoin=500,
          costBlue=70,
      },
    },
  },
  [81]={
    skillName=[[皇极刀法]],
    type=[[主动技能]],
    cdTime=[[20秒]],
    distance=[[近身攻击]],
    describe=[[瞬间释放出强大的刀气，攻击直线上4个目标，需要20秒的技能冷却时间]],
    describe2=[[战士<COLOR VALUE=FF00FF7F>直线穿透</COLOR>技能，瞬间释放出强大的刀气，化作一道光影，突袭身前直线<COLOR VALUE=FF00FF7F>4</COLOR>格内的敌人，是一种破坏力极强的远距离攻击，每次使用后，它需要<COLOR VALUE=FF00FF7F>20</COLOR>秒的冷却时间！]],
    advanced = 1,
	level={
      [1]={
          limitLevel=75,
	  goldCoin=1,
          costBlue=70,
	  skillpage=150,
      },
      [2]={
          limitLevel=75,
	  goldCoin=1,
          costBlue=70,
	  skillpage=150,
      },
      [3]={
          limitLevel=80,
	  goldCoin=1,
          costBlue=70,
	  skillpage=225,
      },
      [4]={
          limitLevel=85,
	  goldCoin=1,
          costBlue=70,
	  skillpage=337,
      },
    },
  },
  [27]={
    skillName=[[霸道冲锋]],
    type=[[主动技能]],
    cdTime=[[2秒]],
    distance=[[近身攻击]],
    describe=[[利用强壮的体格撞开前方两格低等级的目标，技能间隔2秒]],
    describe2=[[战士基本技能，学习后可以霸道的利用强壮的体格<COLOR VALUE=FF00FF7F>撞开</COLOR>前方两格低等级目标，在追杀和群体对战中，起到至关重要的作用，每隔<COLOR VALUE=FF00FF7F>2秒</COLOR>可以使用一次！]],
    level={
      [1]={
          limitLevel=51,
          goldCoin=10,
          costBlue=16,
      },
      [2]={
          limitLevel=51,
          goldCoin=10,
          costBlue=21,
      },
      [3]={
          limitLevel=63,
          goldCoin=20,
          costBlue=25,
      },
      [4]={
          limitLevel=76,
          goldCoin=50,
          costBlue=30,
      },
    },
  },
    [32]={
    skillName=[[不死之身]],
    type=[[被动技能]],
    cdTime=[[600秒]],
    distance=nil,
    describe=[[濒临死亡时，战斗意志仍未消亡，短时间内人物承受再多的伤害都不会死亡；(有涅槃神戒效果时，优先触发涅槃神戒效果)]],
    describe2=[[战士高级技能，濒临死亡时，战斗意志仍未消亡，学习后可以在血量为零时触发，短时间承受再多的伤害都<COLOR VALUE=FF00FF7F>不会死亡</COLOR>，极限反杀必备技能，技能等级越高，持续时间越长，触发冷却时间越短！]],
    advanced = 1,
    level={
      [1]={
          limitLevel=100,
          goldCoin=1,
          costBlue=0,
          skillpage=150,
      },
      [2]={
          limitLevel=100,
          goldCoin=1,
          costBlue=0,
          skillpage=188,
      },
      [3]={
          limitLevel=100,
          goldCoin=1,
          costBlue=0,
          skillpage=225,
      },
      [4]={
          limitLevel=100,
          goldCoin=1,
          costBlue=0,
          skillpage=337,
      },
    },
  },
   [34]={
    skillName=[[鲜血壁垒]],
    type=[[被动技能]],
    cdTime=[[0秒]],
    distance=nil,
    describe=[[磨练出更加坚硬的身体，永久提升暴击抵抗属性;<BR>           LV1:<COLOR VALUE=FF00FF7F>3%</COLOR>           LV2:<COLOR VALUE=FF00FF7F>6%</COLOR><BR>           LV3:<COLOR VALUE=FF00FF7F>9%</COLOR>           LV4:<COLOR VALUE=FF00FF7F>12%</COLOR>]],
    describe2=[[战士高级生存技能，永久提升自身<COLOR VALUE=FF00FF7F>暴击抵抗属性</COLOR>，技能等级越高，提升的暴击抵抗属性越高！]],
    advanced = 1,
     level={
      [1]={
          limitLevel=100,
          goldCoin=1,
          costBlue=0,
          skillpage=150,
      },
      [2]={
          limitLevel=100,
          goldCoin=1,
          costBlue=0,
          skillpage=188,
      },
      [3]={
          limitLevel=100,
          goldCoin=1,
          costBlue=0,
          skillpage=225,
      },
      [4]={
          limitLevel=100,
          goldCoin=1,
          costBlue=0,
          skillpage=337,
      },
    },
  },
  [1]={
    skillName=[[紫焰术]],
    type=[[主动技能]],
    cdTime=[[1.3秒]],
    distance=[[远程攻击]],
    describe=[[召唤高温火球对敌人进行常规伤害]],
    describe2=[[法师<COLOR VALUE=FF00FF7F>远程单体攻击</COLOR>技能，学习后可召唤紫色的高温火球对目标进行攻击，挥舞法杖时，火球激射而出，砸向目标，对目标造成伤害！]],
    level={
      [1]={
          limitLevel=2,
          goldCoin=1,
          costBlue=20,
      },
      [2]={
          limitLevel=2,
          goldCoin=1,
          costBlue=30,
      },
      [3]={
          limitLevel=3,
          goldCoin=2,
          costBlue=40,
      },
      [4]={
          limitLevel=5,
          goldCoin=3,
          costBlue=50,
      },
    },
  },
  [11]={
    skillName=[[召唤天雷]],
    type=[[主动技能]],
    cdTime=[[1.3秒]],
    distance=[[远程攻击]],
    describe=[[召唤一把附着天雷的剑对目标造成剧烈伤害]],
    describe2=[[法师<COLOR VALUE=FF00FF7F>远程单体攻击</COLOR>技能，召唤一把附着雷电之力的剑对目标进行攻击，挥舞法杖时，雷电之剑从天而降，击向目标，对目标造成剧烈伤害，技能等级越高，杀伤力越大！]],
    level={
      [1]={
          limitLevel=16,
          goldCoin=100,
          costBlue=90,
      },
      [2]={
          limitLevel=16,
          goldCoin=100,
          costBlue=120,
      },
      [3]={
          limitLevel=28,
          goldCoin=200,
          costBlue=150,
      },
      [4]={
          limitLevel=41,
          goldCoin=500,
          costBlue=180,
      },
    },
  },
  --[5]={
  --  skillName=[[炙热飞轮]],
  --  type=[[主动技能]],
  --  cdTime=[[1.3秒]],
  --  distance=[[远程攻击]],
  --  describe=[[将火焰压缩并高速旋转，对目标造成剧烈伤害]],
  --  level={
  --    [1]={
  --        limitLevel=20,
  --        goldCoin=10,
  --        costBlue=57,
  --    },
  --    [2]={
  --        limitLevel=20,
  --        goldCoin=20,
  --        costBlue=65,
  --    },
  --    [3]={
  --        limitLevel=20,
  --        goldCoin=40,
  --        costBlue=72,
  --    },
  --    [4]={
  --        limitLevel=40,
  --        goldCoin=40,
  --        costBlue=80,
  --    },
  --  },
  --},
  --[23]={
  --  skillName=[[火凤燎原]],
  --  type=[[主动技能]],
  --  cdTime=[[1.3秒]],
  --  distance=[[远程攻击]],
  --  describe=[[召唤火凤攻击目标点周围4个单位]],
  --  level={
  --    [1]={
  --        limitLevel=51,
  --        goldCoin=400,
  --        costBlue=137,
  --    },
  --    [2]={
  --        limitLevel=51,
  --       goldCoin=600,
  --        costBlue=175,
  --    },
  --    [3]={
  --        limitLevel=63,
  --        goldCoin=800,
  --        costBlue=212,
  --    },
  --    [4]={
  --        limitLevel=76,
  --        goldCoin=2000,
  --        costBlue=250,
  --    },
  --  },
  --},
  [24]={
    skillName=[[雷光风暴]],
    type=[[主动技能]],
    cdTime=[[2秒]],
    distance=[[近身攻击]],
    describe=[[以自身为中心点释放强大的雷电神力，麻痹自身周围的目标]],
    describe2=[[法师<COLOR VALUE=FF00FF7F>近身群体攻击</COLOR>技能，以自身为中心点释放强大雷电神力，伤害麻痹所有围在身边的敌人，攻击的威力以爆发核心最高，最多同时伤害人数可达<COLOR VALUE=FF00FF7F>8</COLOR>人]],
    level={
      [1]={
          limitLevel=64,
          goldCoin=400,
          costBlue=287,
      },
      [2]={
          limitLevel=64,
          goldCoin=400,
          costBlue=375,
      },
      [3]={
          limitLevel=76,
          goldCoin=800,
          costBlue=462,
      },
      [4]={
          limitLevel=89,
          goldCoin=2000,
          costBlue=550,
      },
    },
  },
  [31]={
    skillName=[[法力盾]],
    type=[[主动技能]],
    cdTime=[[1.5秒]],
    distance=nil,
    describe=[[凝聚深厚的法力形成护盾，能抵抗部分伤害]],
    describe2=[[法师<COLOR VALUE=FF00FF7F>防御</COLOR>技能，学习后可以将自身法力凝聚成一个魔法盾来减低伤害。挥舞法杖时，法力凝聚成的魔法盾会从头到脚将施法者紧紧包裹住，抵抗一切物理和魔法攻击！]],
    level={
      [1]={
          limitLevel=37,
          goldCoin=10,
          costBlue=80,
      },
      [2]={
          limitLevel=37,
          goldCoin=10,
          costBlue=130,
      },
      [3]={
          limitLevel=49,
          goldCoin=20,
          costBlue=180,
      },
      [4]={
          limitLevel=62,
          goldCoin=50,
          costBlue=230,
      },
    },
  },
  [33]={
    skillName=[[火凤咆哮]],
    type=[[主动技能]],
    cdTime=[[1.3秒]],
    distance=[[远程攻击]],
    describe=[[召唤火凤对目标点范围进行剧烈攻击]],
    describe2=[[法师<COLOR VALUE=FF00FF7F>群体攻击</COLOR>技能，学习后可召唤强力的紫色火凤，伤害法术区域内的任何生物，挥舞法杖时，火凤从天而降，对目标造成剧烈伤害！技能等级越高，杀伤力越大！]],
    level={
      [1]={
          limitLevel=26,
          goldCoin=200,
          costBlue=330,
      },
      [2]={
          limitLevel=26,
          goldCoin=200,
          costBlue=360,
      },
      [3]={
          limitLevel=38,
          goldCoin=400,
          costBlue=390,
      },
      [4]={
          limitLevel=51,
          goldCoin=1000,
          costBlue=420,
      },
    },
  },
   [88]={
     skillName=[[暴雨流星]],
     type=[[主动技能]],
     cdTime=[[1.3秒]],
     distance=[[远程攻击]],
     describe=[[对目标点3*3范围单位进行惨烈的陨石攻击]],
     describe2=[[法师<COLOR VALUE=FF00FF7F>群体强攻</COLOR>技能，拥有超越火凤咆哮之上的恐怖威力，挥舞法杖时，带着火焰的流星陨石从天而降，对目标范围进行<COLOR VALUE=FF00FF7F>惨烈攻击</COLOR>！技能等级越高，对目标造成的伤害越大！]],
     advanced = 1,
	 level={
       [1]={
           limitLevel=75,
	   goldCoin=1,
           costBlue=352,
	   skillpage=25,
       },
       [2]={
           limitLevel=75,
	    goldCoin=1,
           costBlue=390,
	   skillpage=25,
       },
       [3]={
           limitLevel=80,
	   goldCoin=1,
           costBlue=427,
	   skillpage=37,
       },
       [4]={
           limitLevel=85,
	   goldCoin=1,
           costBlue=465,
	   skillpage=56,
       },
     },
   },
  [22]={
    skillName=[[紫焰陷阱]],
    type=[[主动技能]],
    cdTime=[[1.5秒]],
    distance=[[远程攻击]],
    describe=[[对目标地点放置一道火焰之墙，对上面的目标造成持续伤害]],
    describe2=[[法师<COLOR VALUE=FF00FF7F>群体攻击</COLOR>技能，学习后可以召唤一道紫色的火焰辅助攻击目标，召唤出的火焰会对上面的目标造成持续伤害，技能的等级越高，对火焰上的目标造成的伤害越大！]],
    level={
      [1]={
          limitLevel=51,
          goldCoin=400,
          costBlue=300,
      },
      [2]={
          limitLevel=51,
          goldCoin=400,
          costBlue=350,
      },
      [3]={
          limitLevel=63,
          goldCoin=800,
          costBlue=400,
      },
      [4]={
          limitLevel=76,
          goldCoin=2000,
          costBlue=450,
      },
    },
  },
  [35]={
    skillName=[[燃灵天雷]],
    type=[[被动技能]],
    cdTime=[[0秒]],
    distance=nil, 
    describe=[[使用技能“召唤天雷”时，会根据造成的伤害扣除被攻击目标的法力值<BR>  LV1:最终伤害的<COLOR VALUE=FF00FF7F>1%</COLOR>          LV2:最终伤害的<COLOR VALUE=FF00FF7F>2%</COLOR><BR>  LV3:最终伤害的<COLOR VALUE=FF00FF7F>3%</COLOR>          LV4:最终伤害的<COLOR VALUE=FF00FF7F>4%</COLOR> ]],
    describe2=[[法师高级技能，学习后沟通天雷，召唤一把附着雷电之力的剑对目标进行攻击时，会根据造成的伤害扣除被攻击目标的<COLOR VALUE=FF00FF7F>法力值</COLOR>，技能等级越高，扣除被攻击目标的法力值越多！]],
    advanced = 1,
     level={
      [1]={
          limitLevel=100,
          goldCoin=1,
          costBlue=0,
          skillpage=150,
      },
      [2]={
          limitLevel=100,
          goldCoin=1,
          costBlue=0,
          skillpage=188,
      },
      [3]={
          limitLevel=100,
          goldCoin=1,
          costBlue=0,
          skillpage=225,
      },
      [4]={
          limitLevel=100,
          goldCoin=1,
          costBlue=0,
          skillpage=337,
      },
    },
  },
    [36]={
    skillName=[[凝神归元]],
    type=[[被动技能]],
    cdTime=[[600秒]],
    distance=nil,
    describe=[[法力值为零时触发该技能，瞬间回复部分法力值；技能有<COLOR VALUE=FF00FF7F>600秒</COLOR>的触发冷却时间；<BR>LV1:回复总法力值的<COLOR VALUE=FF00FF7F>10%</COLOR>    LV2:回复总法力值的<COLOR VALUE=FF00FF7F>20%</COLOR><BR>LV3:回复总法力值的<COLOR VALUE=FF00FF7F>30%</COLOR>    LV4:回复总法力值的<COLOR VALUE=FF00FF7F>40%</COLOR> ]],
    describe2=[[法师高级技能，学习后沟通天地灵气，法力值为零时可瞬间吸收天地灵气，<COLOR VALUE=FF00FF7F>回复</COLOR>部分法力值；技能每次触发间隔为<COLOR VALUE=FF00FF7F>600秒</COLOR>，技能等级越高，回复的法力值越多，！]],
    advanced = 1,
     level={
      [1]={
          limitLevel=100,
          goldCoin=1,
          costBlue=0,
          skillpage=150,
      },
      [2]={
          limitLevel=100,
          goldCoin=1,
          costBlue=0,
          skillpage=188,
      },
      [3]={
          limitLevel=100,
          goldCoin=1,
          costBlue=0,
          skillpage=225,
      },
      [4]={
          limitLevel=100,
          goldCoin=1,
          costBlue=0,
          skillpage=337,
      },
    },
  },
  [2]={
    skillName=[[内力疗伤]],
    type=[[主动技能]],
    cdTime=[[1.3秒]],
    distance=[[远程攻击]],
    describe=[[剑客利用内力帮助目标恢复生命值]],
    describe2=[[剑客<COLOR VALUE=FF00FF7F>治疗</COLOR>技能，学习后可以使用内力给自己治疗，触发技能时，内力会产生一股复苏之力包围自己，持续恢复，技能等级越高，恢复的速度越快！]],
    level={
      [1]={
          limitLevel=26,
          goldCoin=200,
          costBlue=17,
      },
      [2]={
          limitLevel=26,
          goldCoin=200,
          costBlue=35,
      },
      [3]={
          limitLevel=38,
          goldCoin=400,
          costBlue=52,
      },
      [4]={
          limitLevel=51,
          goldCoin=1000,
          costBlue=70,
      },
    },
  },
  [4]={
    skillName=[[剑客心法]],
    type=[[被动技能]],
    cdTime=[[0秒]],
    distance=nil,
    describe=[[剑客挖掘自身的潜能，随技能等级提升，便能发挥出更多的有效伤害]],
    describe2=[[剑客入门心法，挖掘自身潜能，在修炼过程中领悟的心法，技能等级越高获得的有效伤害值越高！]],
    level={
      [1]={
          limitLevel=37,
          goldCoin=1,
          costBlue=0,
      },
      [2]={
          limitLevel=37,
          goldCoin=1,
          costBlue=0,
      },
      [3]={
          limitLevel=49,
          goldCoin=2,
          costBlue=0,
      },
      [4]={
          limitLevel=62,
          goldCoin=3,
          costBlue=0,
      },
    },
  },
  [6]={
    skillName=[[剑气噬体]],
    type=[[主动技能]],
    cdTime=[[1.3秒]],
    distance=[[远程攻击]],
    describe=[[将一股剑气逼入目标体内，使目标受到持续伤害和降低防御]],
    describe2=[[剑客基本技能，触发技能时，一道剑气击向目标，使得目标全身发绿，并受到<COLOR VALUE=FF00FF7F>持续伤害和降低防御</COLOR>，剑客的攻击力越强，噬体效果对目标的有效时间越长，对目标的持续伤害越大！]],
    level={
      [1]={
          limitLevel=5,
          goldCoin=100,
          costBlue=10,
      },
      [2]={
          limitLevel=5,
          goldCoin=100,
          costBlue=20,
      },
      [3]={
          limitLevel=17,
          goldCoin=200,
          costBlue=30,
      },
      [4]={
          limitLevel=30,
          goldCoin=500,
          costBlue=40,
      },
    },
  },
  [13]={
    skillName=[[太极剑气]],
    type=[[主动技能]],
    cdTime=[[1.3秒]],
    distance=[[远程攻击]],
    describe=[[剑客使用太极剑气攻击目标，随攻击力提升伤害值]],
    describe2=[[剑客<COLOR VALUE=FF00FF7F>远程单体攻击</COLOR>技能，学习后可以使用剑气远程攻击敌人，触发技能时，剑气激射而出，幻化成剑，对目标造成巨大伤害，技能等级越高，对目标的伤害越大！]],
    level={
      [1]={
          limitLevel=2,
          goldCoin=1,
          costBlue=32,
      },
      [2]={
          limitLevel=2,
          goldCoin=1,
          costBlue=45,
      },
      [3]={
          limitLevel=3,
          goldCoin=2,
          costBlue=57,
      },
      [4]={
          limitLevel=5,
          goldCoin=3,
          costBlue=70,
      },
    },
  },
  [17]={
    skillName=[[召唤剑奴]],
    type=[[主动技能]],
    cdTime=[[1.5秒]],
    distance=nil,
    describe=[[剑客可以沟通心灵，召唤剑奴为自己战斗]],
    describe2=[[剑客召唤技能，学习后可以召唤出剑奴陪同作战，召唤出的剑奴将会成为剑客最忠诚的跟随者，并且与主人心灵相通，剑奴死亡后，主人可以使用自身内力将剑奴复活！]],
    level={
      [1]={
          limitLevel=16,
          goldCoin=1,
          costBlue=120,
      },
      [2]={
          limitLevel=16,
          goldCoin=1,
          costBlue=160,
      },
      [3]={
          limitLevel=28,
          goldCoin=1,
          costBlue=200,
      },
      [4]={
          limitLevel=41,
          goldCoin=1,
          costBlue=240,
      },
    },
  },
  [14]={
    skillName=[[御魔护体阵]],
    type=[[主动技能]],
    cdTime=[[1.3秒]],
    distance=nil,
    describe=[[帮助目标点3*3范围内的玩家吸收物理和魔法伤害]],
    describe2=[[剑客<COLOR VALUE=FF00FF7F>防御</COLOR>技能。学习后可以将内力幻化为剑阵守护自己和其他玩家，一段时间内帮助吸收物理和魔法伤害。它的有效时间随训练等级和剑客战斗力的提高而提高。]],
    level={
      [1]={
          limitLevel=51,
          goldCoin=50,
          costBlue=37,
      },
      [2]={
          limitLevel=51,
          goldCoin=50,
          costBlue=75,
      },
      [3]={
          limitLevel=63,
          goldCoin=100,
          costBlue=112,
      },
      [4]={
          limitLevel=76,
          goldCoin=250,
          costBlue=150,
      },
    },
  },
--  [15]={
--    skillName=[[御魔剑阵]],
--    type=[[被动技能]],
--    cdTime=[[1.3秒]],
--    distance=nil,
--    describe=[[帮助目标点3*3范围内的玩家吸收物理攻击伤害]],
--    level={
--      [1]={
--          limitLevel=35,
--          goldCoin=10,
--          costBlue=37,
--      },
--      [2]={
--          limitLevel=35,
--          goldCoin=20,
--          costBlue=75,
--      },
--      [3]={
--          limitLevel=35,
--          goldCoin=40,
--          costBlue=112,
--      },
--      [4]={
--          limitLevel=40,
--          goldCoin=40,
--          costBlue=150,
--      },
--    },
--  },
  [29]={
    skillName=[[群体疗伤]],
    type=[[主动技能]],
    cdTime=[[1.3秒]],
    distance=[[远程攻击]],
    describe=[[剑客运用内力，帮助目标点3*3范围内玩家恢复生命值]],
    describe2=[[剑客<COLOR VALUE=FF00FF7F>群体治疗</COLOR>技能，学习后能够将内力幻化成古老的符文绽放在目标脚下，符文产生的生命之力会持续恢复目标和目标周围玩家的HP和MP，治疗效果随技能等级增加而增加！]],
    level={
      [1]={
          limitLevel=80,
          goldCoin=200,
          costBlue=280,
      },
      [2]={
          limitLevel=80,
          goldCoin=200,
          costBlue=310,
      },
      [3]={
          limitLevel=85,
          goldCoin=400,
          costBlue=340,
      },
      [4]={
          limitLevel=90,
          goldCoin=1000,
          costBlue=370,
      },
    },
  },
  [30]={
    skillName=[[召唤剑侍]],
    type=[[主动技能]],
    cdTime=[[1.5秒]],
    distance=nil,
    describe=[[剑客的能力得到提升，可以召唤剑侍为自己战斗]],
    describe2=[[剑客高级召唤技能。学习后可以召唤出攻击力和爆发力比剑奴更强的剑侍，剑侍将会成为剑客最忠诚的跟随者，并且与主人心灵相通，剑侍死亡后，主人可以使用自身内力将她复活]],
    level={
      [1]={
          limitLevel=70,
          goldCoin=1,
          costBlue=280,
      },
      [2]={
          limitLevel=70,
          goldCoin=1,
          costBlue=320,
      },
      [3]={
          limitLevel=75,
          goldCoin=1,
          costBlue=360,
      },
      [4]={
          limitLevel=80,
          goldCoin=1,
          costBlue=400,
      },
    },
  },
  [89]={
    skillName=[[召唤剑灵]],
    type=[[主动技能]],
    cdTime=[[1.5秒]],
    distance=nil,
    describe=[[召唤剑器之灵辅助自己攻击，剑灵为法术攻击]],
    describe2=[[剑客<COLOR VALUE=FF00FF7F>超级召唤</COLOR>技能，剑灵是由上古神剑中的一缕魂魄幻化而成，拥有强大的攻击力和爆发力，剑灵将会成为剑客最忠诚的跟随者，并且与主人心灵相通，剑灵死亡后，主人可以使用自身内力将她复活！]],
    advanced = 1,
	level={
      [1]={
          limitLevel=75,
          goldCoin=1,
          costBlue=280,
	  skillpage=25,
      },
      [2]={
          limitLevel=75,
          goldCoin=1,
          costBlue=320,	 
      },
	  [3]={
          limitLevel=80,
          goldCoin=1,
          costBlue=360,	  
      },
      [4]={
          limitLevel=85,
          goldCoin=1,
          costBlue=1,	  
      },
    },
  },
  [18]={
    skillName=[[万里无踪]],
    type=[[主动技能]],
    cdTime=[[1.3秒]],
    distance=nil,
    describe=[[剑客玄妙的身法可以让自己进入隐身状态，移动或攻击则隐身失效]],
    describe2=[[剑客基本技能，剑宗在东瀛忍术基础上创造的新技能，学习后，可以使用绝妙的身法让自己进入<COLOR VALUE=FF00FF7F>隐身</COLOR>状态，使怪物无法察觉，是攻击大BOSS时的保命技能！]],
    level={
      [1]={
          limitLevel=64,
          goldCoin=200,
          costBlue=12,
      },
      [2]={
          limitLevel=64,
          goldCoin=200,
          costBlue=25,
      },
      [3]={
          limitLevel=76,
          goldCoin=400,
          costBlue=37,
      },
      [4]={
          limitLevel=89,
          goldCoin=1000,
          costBlue=50,
      },
    },
  },


  [61]={
    skillName=[[战神盾]],
    type=[[主动技能]],
    cdTime=[[1.3秒]],
    distance=nil,
    describe=[[使用后，短时间内大幅提升减免伤害效果，提高生存能力]],
    describe2=[[战士<COLOR VALUE=FF00FF7F>超级防御</COLOR>技能，由第一战士吸取少林精华所创，刀剑不入，符电不伤，拥有超高防御力，提高生存能力，战士当之无愧的第一<COLOR VALUE=FF00FF7F>保命</COLOR>技能！]],
    advanced = 1,
	level={
      [1]={
          limitLevel=75,
	  goldCoin=1,
          costBlue=12,
	  skillpage=25,
      },
      [2]={
          limitLevel=75,
	  goldCoin=1,
          costBlue=25,
	  skillpage=25,
      },
      [3]={
          limitLevel=80,
	  goldCoin=1,
          costBlue=37,
	  skillpage=37,
      },
      [4]={
          limitLevel=85,
	  goldCoin=1,
          costBlue=50,
	  skillpage=56,
      },
    },
  },


  [57]={
    skillName=[[剑开天门]],
    type=[[主动技能]],
    cdTime=[[1.3秒]],
    distance=[[远程攻击]],
    describe=[[对目标造成强大的伤害，同时对目标周围单位造成溅射伤害]],
    describe2=[[剑客<COLOR VALUE=FF00FF7F>远程群体强攻</COLOR>技能，学习后可以使用内力幻化成剑对目标进行猛烈的范围攻击，对目标造成大量伤害的同时对目标周围目标造成<COLOR VALUE=FF00FF7F>溅射伤害</COLOR>，技能等级越高，对敌人的伤害越大！]],
    advanced = 1,
	level={
      [1]={
          limitLevel=75,
	  goldCoin=1,
          costBlue=495,
	  skillpage=150,
      },
      [2]={
          limitLevel=75,
	  goldCoin=1,
          costBlue=540,
          skillpage=150,
      },
      [3]={
          limitLevel=80,
	  goldCoin=1,
          costBlue=585,
	  skillpage=225,
      },
      [4]={
          limitLevel=85,
	  goldCoin=1,
          costBlue=630,
	  skillpage=337,
      },
    },
  },


  [55]={
    skillName=[[玄冰真气]],
    type=[[主动技能]],
    cdTime=[[1.3秒]],
    distance=[[远程攻击]],
    describe=[[攻击目标的同时，有几率使其冰冻]],
    describe2=[[法师<COLOR VALUE=FF00FF7F>远程单体攻击</COLOR>技能，学习后攻击目标的同时，有几率使其<COLOR VALUE=FF00FF7F>冰冻</COLOR>，触发技能时，召唤出的冰凤凰狠狠砸向目标，并有几率将目标冰冻，技能的等级越高，将目标冰冻住的几率越大。]],
    advanced = 1,
	level={
      [1]={
          limitLevel=75,
	  goldCoin=1,
          costBlue=90,
	  skillpage=150,
      },
      [2]={
          limitLevel=75,
	  goldCoin=1,
          costBlue=120,
	  skillpage=150,
      },
      [3]={
          limitLevel=80,
	  goldCoin=1,
          costBlue=150,
	  skillpage=225,
      },
      [4]={
          limitLevel=85,
	  goldCoin=1,
          costBlue=180,
	  skillpage=337,
      },
    },
  },
[37]={
    skillName=[[一气化三清]],
    type=[[主动技能]],
    cdTime=[[1.3秒]],
    distance=nil,
    describe=[[可分身出2个跟自身一样的人物出来，其他勇士无法分辨真伪(自身可分辨），同时附加1秒无敌状态;技能等级越高，冷却时间越短，分身实力越强，持续时间越长；]],
    describe2=[[剑客高级技能，学习后可掌握高级法术分身术，使用技能可幻化出<COLOR VALUE=FF00FF7F>两个</COLOR>分身，混淆别人视野，附加<COLOR VALUE=FF00FF7F>1秒</COLOR>无敌状态，保命和追杀必备的超强技能，技能等级越高，冷却时间越短，分身实力越强，持续时间越长！]],
    advanced = 1,
 level={
      [1]={
          limitLevel=100,
          goldCoin=1,
          costBlue=495,
          skillpage=150,
      },
      [2]={
          limitLevel=100,
          goldCoin=1,
          costBlue=540,
          skillpage=188,
      },
      [3]={
          limitLevel=100,
          goldCoin=1,
          costBlue=585,
          skillpage=225,
      },
      [4]={
          limitLevel=100,
          goldCoin=1,
          costBlue=630,
          skillpage=337,
      },
    },
  },
[38]={
    skillName=[[闪展腾挪]],
    type=[[被动技能]],
    cdTime=[[0秒]],
    distance=nil,
    describe=[[一定概率免疫法师职业的紫焰术、召唤天雷、火凤咆哮、暴雨流星、玄冰真气技能伤害;<BR>    LV1: <COLOR VALUE=FF00FF7F>3%</COLOR>免疫伤害       LV2: <COLOR VALUE=FF00FF7F>7%</COLOR>免疫伤害<BR>    LV3:<COLOR VALUE=FF00FF7F>11%</COLOR>免疫伤害       LV4:<COLOR VALUE=FF00FF7F>15%</COLOR>免疫伤害]],
    describe2=[[剑客终极身法，受到法师职业的紫焰术、召唤天雷、火凤咆哮、暴雨流星、玄冰真气技能攻击时，有一定概率<COLOR VALUE=FF00FF7F>免疫技能伤害</COLOR>，技能等级越高，免疫概率也越高]],
    advanced = 1,
 level={
      [1]={
          limitLevel=100,
          goldCoin=1,
          costBlue=0,
          skillpage=150,
      },
      [2]={
          limitLevel=100,
          goldCoin=1,
          costBlue=0,
          skillpage=188,
      },
      [3]={
          limitLevel=100,
          goldCoin=1,
          costBlue=0,
          skillpage=225,
      },
      [4]={
          limitLevel=100,
          goldCoin=1,
          costBlue=0,
          skillpage=337,
      },
    },
  },
--  [99]={
--    skillName=[[群体施毒术]],
--    type=[[主动技能]],
--    cdTime=[[1.3秒]],
--    distance=[[远程攻击]],
--    describe=[[对敌对目标及其周围1格范围内目标造成中毒效果]],
--    level={
--      [1]={
--          limitLevel=75,
--          goldCoin=10,
--          costBlue=12,
--      },
--      [2]={
--          limitLevel=75,
--         goldCoin=20,
--          costBlue=25,
--      },
--      [3]={
--          limitLevel=75,
--          goldCoin=40,
--          costBlue=37,
--     },
--      [4]={
--          limitLevel=75,
--          goldCoin=40,
--          costBlue=50,
--      },
--    },
--  },
}
