MAXPOOLLINE=958
Guild_Answer_config={
[1]={question="作为“六朝古都”，历史上在什么朝代，南京城定名为“南京”？",answer={"A 隋朝","B 明朝","C 唐朝","D 宋朝"},result=2},
[2]={question="佐罗的面具遮住嘴巴没有？",answer={"A 有","B 没有"},result=2},
[3]={question="左传、公羊传、谷梁传三部书，是哪本书的演绎？",answer={"A 春秋","B 尚书","C 诗经","D 史记"},result=1},
[4]={question="遵议会议召开于？",answer={"A 长征之前","B 长征开始时","C 长征途中","D 长征结束后"},result=3},
[5]={question="最早系统地确定官职的是在：",answer={"A 商朝","B 西周初期","C 春秋","D 汉朝初期"},result=2},
[6]={question="最早干洗衣物是用？",answer={"A 柴油","B 汽油","C 牛油","D 鱼油"},result=2},
[7]={question="最早的锁是？",answer={"A 铜锁","B 木锁","C 金锁","D 玉锁"},result=2},
[8]={question="最早的四冲程内燃机用的是什么燃料？",answer={"A 酒精","B 煤气","C 汽油","D 柴油"},result=2},
[9]={question="最早的剑出现在距约今多少年前？",answer={"A 6000年","B 8000年","C 7000年"},result=1},
[10]={question="最早出现在今云南省境内的人类是（）。",answer={"A 元谋人","B 蓝田人","C 丁村人","D 半坡人"},result=1},
[11]={question="最清洁的能源是：？",answer={"A 石油","B 天然气","C 太阳能","D 地热能"},result=3},
[12]={question="最能反映骨骼发育的重要指标是",answer={"A 胸围","B 牙齿数","C 坐高","D 身长"},result=4},
[13]={question="最耐日晒的织品是哪一种？",answer={"A 苎麻","B 腈纶","C 羊毛","D 涤纶"},result=2},
[14]={question="最古老的医院是设在：",answer={"A 学校里","B 教堂里","C 宫廷里","D 集市里"},result=2},
[15]={question="最低几级可以结婚？",answer={"A 22级","B 18级","C 1级"},result=3},
[16]={question="走私、贩卖、运输、制造多少克毒品是犯罪行为？",answer={"A 无论数量多少","B 50克以上"},result=1},
[17]={question="总角之交是指：",answer={"A 顽童之交","B 少年之交","C 中年之交","D 忘年之交"},result=2},
[18]={question="自然科学中最早出现的是：",answer={"A 数学","B 物理学","C 天文学","D 医学"},result=3},
[19]={question="自然带最明显的标志是？",answer={"A 气温","B 植物","C 动物","D 地形"},result=2},
[20]={question="紫毫毛笔的“紫毫”是什么动物的毛？",answer={"A 兔","B 猪","C 牛","D 狼"},result=1},
[21]={question="子曰：吾十有五而志于学，三十而立，四十而（）。",answer={"A 不惑","B 知天命","C 耳顺"},result=1},
[22]={question="铸造青铜剑不需要以下哪种矿石？",answer={"A 硫","B 锡","C 铅"},result=1},
[23]={question="著名画家徐悲鸿最擅长画的是马吗？",answer={"A 是","B 不是"},result=1},
[24]={question="著名的张家界位于？",answer={"A 湖南","B 湖北","C 河北"},result=1},
[25]={question="著名的景点十三陵是哪个朝代修建的？",answer={"A 明朝","B 元朝"},result=1},
[26]={question="著名的二胡曲《二泉映月》的作者是谁？",answer={"A 刘天华","B 阿炳","C 聂耳","D 冼星海"},result=2},
[27]={question="属于儒家思想的是？",answer={"A 仁者爱人","B 无为而治","C 法不阿贵","D 兼爱，非攻"},result=1},
[28]={question="属于国家一类保护动物的是？",answer={"A 天鹅","B 娃娃鱼","C 孔雀","D 丹顶鹤"},result=4},
[29]={question="珠峰的高度是多少？",answer={"A 8878千米","B 8948千米","C 8848千米","D 8841千米"},result=3},
[30]={question="朱熹的《观书有感》中“问渠那得清如许”的下句是？",answer={"A 为有源头清水来","B 为有活水源头来","C 为有源头活水来"},result=3},
[31]={question="昼为阳，夜为阴，则下午为（）。",answer={"A 阳中之阴","B 阳中之阳","C 辰","D 阴中之阳"},result=1},
[32]={question="仕宦当作执金吾，娶妻当得阴丽华，是谁说的？",answer={"A 刘彻","B 刘秀"},result=2},
[33]={question="重阳是我国人民的传统节日，请问“重阳”二字源自？",answer={"A 《诗经》","B 《易经》"},result=2},
[34]={question="重阳节，人们有登高、赏菊、插茱萸和喝什么酒的风俗？",answer={"A 雄黄酒","B 菊花酒","C 黄酒"},result=2},
[35]={question="终止禅让制的是（）。",answer={"A 禹","B 启","C 纣","D 汤"},result=2},
[36]={question="中药业的祖师是谁？",answer={"A 扁鹊","B 李时珍"},result=2},
[37]={question="中提琴是西洋乐器吗？",answer={"A 是","B 不是"},result=1},
[38]={question="中山陵在哪座山上？",answer={"A 南京钟山","B 南京中山"},result=1},
[39]={question="中华鲟和恐龙哪一个在地球上出现的早？",answer={"A 恐龙","B 中华鲟"},result=2},
[40]={question="中国最早的无声电影是哪一部片子？",answer={"A 《黑籍冤魂》","B 《定军山》","C 《庄子与其妻》"},result=2},
[41]={question="中国最热的地方在哪里？",answer={"A 四川盆地","B 长江中下游","C 吐鲁番盆地","D 海南岛"},result=3},
[42]={question="中国最大的戏楼是在颐和园对吗？",answer={"A 对","B 不对"},result=1},
[43]={question="中国最大的湖泊是？",answer={"A 青海湖","B 洞庭湖","C 鄱阳湖"},result=1},
[44]={question="中国最长的叙事长诗是哪一部？",answer={"A 《孔雀东南飞》","B 《诗经》","C 《琵琶行》"},result=1},
[45]={question="中国在哪一年对香港恢复行使主权？",answer={"A 1997","B 1998"},result=1},
[46]={question="中国在国际货币基金组织中属于：",answer={"A 观察员","B 正式成员","C 准成员","D 非成员"},result=2},
[47]={question="中国无声影片的最高峰《神女》是谁的代表作？",answer={"A 胡蝶","B 阮玲玉","C 上官云珠","D 张瑞芳"},result=2},
[48]={question="中国虽然不是双姓大国，但还是有不少双姓，请问以下哪个不是双姓？",answer={"A 东郭","B 诸葛","C 羊舌","D 三台"},result=4},
[49]={question="中国四大名砚中哪一种不是石砚？",answer={"A 端砚","B 洮河砚","C 澄泥砚","D 歙泥"},result=3},
[50]={question="中国神话传说中人类的始祖是？",answer={"A 女娃","B 女娲氏"},result=2},
[51]={question="中国农业银行发行的信用卡是哪一个？",answer={"A 长城卡","B 金穗卡","C 牡丹卡","D 龙卡"},result=2},
[52]={question="中国农业银行发行的信用卡是？",answer={"A 牡丹卡","B 龙卡","C 绿卡","D 金穗卡"},result=4},
[53]={question="中国哪位皇帝最长寿？",answer={"A 乾隆","B 武则天","C 康熙","D 忽必烈"},result=1},
[54]={question="中国历史上的“八大山人”指的是八个人吗？",answer={"A 是","B 不是"},result=2},
[55]={question="中国疆都最早、历史最长、朝代最多的古城是？",answer={"A 长安","B 洛阳"},result=2},
[56]={question="中国建设银行发行的信用卡是哪一个？",answer={"A 长城卡","B 金穗卡","C 牡丹卡","D 龙卡"},result=4},
[57]={question="中国古建筑学科的开拓者是：",answer={"A 鲁班","B 梁思成","C 杨廷玉","D 童寓"},result=2},
[58]={question="中国古代把皇帝称做真龙天子是从谁开始的？",answer={"A 秦始皇","B 汉高祖","C 商纣王","D 尧"},result=2},
[59]={question="中国共产党的第十六次代表大会于11月多少日举行？",answer={"A 5","B 8","C 11","D 15"},result=2},
[60]={question="中国工商银行可以发行货币吗？",answer={"A 可以","B 不可以"},result=2},
[61]={question="中国工商银行发行的信用卡是？",answer={"A 京穗卡","B 牡丹卡","C 龙卡","D 绿卡"},result=2},
[62]={question="中国端阳节有用雄黄酒灭五毒的习惯，那么雄黄酒可以饮用吗？",answer={"A 可以","B 不可以"},result=2},
[63]={question="中国第一座核电站叫什么名字？",answer={"A 秦山核电站","B 大亚湾核电站"},result=1},
[64]={question="中国第一座佛教寺院是哪一座？",answer={"A 洛阳白马寺","B 北京潭柘寺","C 五台山清凉寺","D 蒿山少林寺"},result=1},
[65]={question="中国第一座电影院是？",answer={"A 北京大华电影院","B 上海虹口电影院","C 北京广和电影院"},result=2},
[66]={question="中国第一部纪传体通史是？",answer={"A 史记","B 中国通史","C 儒林外史"},result=1},
[67]={question="中国第一部彩色故事片是？",answer={"A 《祝福》","B 《女篮五号》","C 《渔光曲》","D 《定军山》"},result=1},
[68]={question="中国的四大发明不包括？",answer={"A 火药","B 指南针","C 活字印刷","D 地动仪"},result=4},
[69]={question="中国的首都是那里？：",answer={"A 北京","B 上海","C 重庆","D 哈尔滨"},result=1},
[70]={question="中国的三大姓分别是？",answer={"A 陈、李、王","B 陈、张、李","C 张、王、李","D 张、林、王"},result=3},
[71]={question="中国的尼姑最早是何时出现的？",answer={"A 夏朝","B 唐朝","C 南北朝","D 金朝"},result=3},
[72]={question="中国的牡丹之乡是哪里？",answer={"A 山东菏泽","B 山东烟台"},result=1},
[73]={question="只要有恒心的下一句是什么？",answer={"A 必定有钱剩","B 铁柱磨成针","C 天下无敌人","D 点石可成金"},result=2},
[74]={question="执行必须以生效的（）为根据？",answer={"A 判决书","B 裁定书","C 调解书","D 法律文书"},result=4},
[75]={question="郑和第一次出使西洋的出发地是（）。",answer={"A 南京","B 广州","C 泉州","D 刘家港"},result=4},
[76]={question="正规围棋比赛的棋盘大小是：",answer={"A 13乘13","B 15乘15","C 19乘19","D 21乘21"},result=3},
[77]={question="这间屋子真埋汰。“埋汰”是：",answer={"A 脏","B 整洁","C 豪华","D 简陋"},result=1},
[78]={question="赵本山2009年的春晚小品叫什么？",answer={"A 卖拐","B 不差钱","C 相亲","D 昨天、今天、明天"},result=2},
[79]={question="武则天的真名称??",answer={"A 礴","B 曌","C 檄"},result=2},
[80]={question="张衡的地动仪有几条龙？",answer={"A 6条","B 8条","C 9条","D 12条"},result=2},
[81]={question="战国史上“合纵”就是六国联合抵抗秦国，倡导“合纵”的是苏秦对吗？",answer={"A 对","B 不对"},result=1},
[82]={question="战国时以下哪个国家的军队用剑剑身最窄？",answer={"A 楚","B 秦","C 赵"},result=2},
[83]={question="战国时期，总结前人医疗经验归纳出四诊法，是名医华佗，对吗？",answer={"A 对","B 不对"},result=2},
[84]={question="战国时郭隗对燕昭王说“请自隗始”，是指他开始干什么呢？",answer={"A 清查财产","B 聘请任用","C 晋升高官","D 撤职查办"},result=2},
[85]={question="曾经沧海难为水，除却巫山不是云是谁的诗词句？",answer={"A 苏东坡","B 元稹","C 白居易","D 李商隐"},result=2},
[86]={question="造纸术是谁发明的？",answer={"A 蔡伦","B 毕升"},result=1},
[87]={question="造成煤气中毒的气体是？",answer={"A 一氧化碳","B 二氧化碳"},result=1},
[88]={question="咱俩嘎点儿啥。“嘎”的意思：",answer={"A 打赌","B 割","C 打扫卫生","D 吃"},result=4},
[89]={question="在我国通常看到的水从水池流下去时形成的漩涡是？",answer={"A 顺时针方向","B 逆时针方向"},result=2},
[90]={question="在中国近代史上，北京曾两次被外国侵略军占领，两位在位皇帝外逃，他们是？",answer={"A 道光,咸丰","B 同治,慈禧","C 咸丰,光绪","D 光绪,宣统"},result=3},
[91]={question="在云南，湖泊习惯上被称为：",answer={"A 淀","B 泊","C 泽","D 海"},result=4},
[92]={question="在鱼的眼睛里，物体是变形的吗？",answer={"A 是","B 不是"},result=1},
[93]={question="在小说《侠客行》中，石破天的玄铁令是从那里得来的？",answer={"A 一块烧饼中","B 一本书中","C 一口井里","D 路上捡到的"},result=1},
[94]={question="王明阳是哪个朝代的人？（）。",answer={"A 明朝","B 元朝","C 宋朝","D 清朝"},result=1},
[95]={question="在我国四川省的南部，有“万里长江第一城”之称的城市是？",answer={"A 宜宾","B 重庆"},result=1},
[96]={question="在我国历史上，最早建立封建专制主义中央集权制度的朝代是？",answer={"A 秦朝","B 汉朝","C 隋朝","D 唐朝"},result=1},
[97]={question="在位时间最短的皇帝是东汉的刘贺，他只当了多久的皇帝就被废除了？",answer={"A 25天","B 26天","C 27天","D 28天"},result=3},
[98]={question="在糖水中加少量盐，尝起来会怎样？",answer={"A 变涩","B 变咸","C 更甜","D 变苦"},result=3},
[99]={question="在太空中，宇航员观察星星时会发现（）。",answer={"A 星光闪烁","B 星星十分清晰","C 有时闪烁，有时清晰","D 当太空舱位于地球和太阳之间时，星光闪烁"},result=2},
[100]={question="在世界上首创用汤药治病的是：",answer={"A 孙思邈","B 扁鹊","C 李时珍","D 伊尹"},result=4},
[101]={question="在生活中，正常人体的五大感觉：视觉、听觉、触觉、味觉和嗅觉，哪一个提供的信息量最大？",answer={"A 视觉","B 听觉","C 触觉","D 嗅觉"},result=1},
[102]={question="在汽车前面供驾驶员看左右和后面车辆的是？",answer={"A 凸镜","B 凹镜"},result=1},
[103]={question="在民事诉讼中，一方当事人私下所录的与对方当事人的谈话录音，能否作为定案证据使用？",answer={"A 能","B 不能"},result=2},
[104]={question="在劳动合同中写有“发生工伤事故责任自负”的条款，是否具有法律效力？",answer={"A 有","B 没有"},result=2},
[105]={question="在九大行星中，被称为最冷的行星是哪一颗？",answer={"A 海王星","B 冥王星","C 天王星"},result=2},
[106]={question="在古希腊神话中，爱与美的女神叫做？",answer={"A 缪斯","B 赫拉","C 雅典娜","D 阿芙洛狄特"},result=4},
[107]={question="在狗的眼睛里世界是什么颜色的？",answer={"A 只有灰色","B 只有彩色","C 只有黑白色"},result=3},
[108]={question="在冰箱内保存胶卷可延长使用寿命吗？",answer={"A 正确","B 不正确"},result=1},
[109]={question="在贝多芬的《第六交响曲》中有暴风雨的场景吗？",answer={"A 有","B 没有"},result=1},
[110]={question="在INTERNET中，域名有很多种类，下面那个属于商业公司的域名的后缀？",answer={"A EXE","B COM","C RPG"},result=2},
[111]={question="在“周处除三害”这个典故里，危害乡里的第三害是：",answer={"A 猛虎","B 蛟龙","C 他自己","D 土匪"},result=3},
[112]={question="在“危如累卵”这个典故中，荀息为了说服晋灵公，把十二个什么东西垒起来，又在上面放了九个？",answer={"A 石子","B 棋子","C 珍珠","D 蜡烛"},result=2},
[113]={question="在“罗雀掘鼠”典故中，人们捕雀挖鼠的目的是：",answer={"A 除害以保护庄稼","B 充饥","C 交给收购者赚钱","D 完成上级命令"},result=2},
[114]={question="在“夸父逐日”中，“夸父”是怎样追逐太阳的？",answer={"A 驾车","B 奔跑","C 飞行","D 骑马"},result=2},
[115]={question="在“精卫填海”的故事里,“精卫”是？",answer={"A 一个人","B 一只鸟","C 一条龙","D 一只猴子"},result=2},
[116]={question="月球上看天空是？",answer={"A 蓝色的","B 灰色的","C 黑色的","D 白色的"},result=3},
[117]={question="圆周率大约值是多少？",answer={"A 0.8664","B 6.22","C 1.7321","D 3.1416"},result=4},
[118]={question="圆舞曲是华尔兹吗？",answer={"A 是","B 不是"},result=1},
[119]={question="元朝最优秀的剧作家是？",answer={"A 李清照","B 窦娥","C 关汉卿","D 汤显祖"},result=3},
[120]={question="遇到有同学传看不良刊物时，正确的做法是（）。",answer={"A 装作没看见","B 跟着一起看","C 自己看后传给别人看","D 我不看也劝同学不看"},result=4},
[121]={question="寓言《坐井观天》中坐在井里的是什么动物？",answer={"A 蜥蜴","B 青蛙","C 水蛭","D 水蛇"},result=2},
[122]={question="语言中最小的声音和意义的结合体称为：",answer={"A 音素","B 音节","C 语素","D 词"},result=3},
[123]={question="雨花石属于玛瑙的一种吗？",answer={"A 是","B 不是"},result=1},
[124]={question="鱼有心脏吗？",answer={"A 有","B 没有"},result=1},
[125]={question="鱼露是一种：",answer={"A 咸味调料","B 甜味调料","C 酸味调料","D 鲜味调料"},result=1},
[126]={question="于某将自家的住房以每月300元的价格租给赵某居住，于某租房的收入需要缴纳房产税吗？",answer={"A 是","B 不是"},result=1},
[127]={question="传送石有什么作用",answer={"A 可以发光照明","B 一块破石头","C 传送各大区域"},result=3},
[128]={question="有钢琴诗人之称的是：",answer={"A 贝多芬","B 海顿","C 莫扎特","D 肖邦"},result=4},
[129]={question="有“圆舞曲之父”称号的作曲家是？",answer={"A 老约翰·斯特劳斯","B 肖邦","C 贝多芬","D 莫扎特"},result=1},
[130]={question="有“小提琴之王”之称的作曲家是？",answer={"A 帕格尼尼","B 贝多芬","C 海顿","D 莫扎特"},result=1},
[131]={question="有“五海三洲之地”之称的是哪里？",answer={"A 西亚","B 南亚","C 中亚","D 东亚"},result=1},
[132]={question="有“世界船王”之称的海外炎黄子孙是指？",answer={"A 王安","B 王贞治","C 杨小燕","D 包玉刚"},result=4},
[133]={question="有“黑金”美誉的燃料是？",answer={"A 煤油","B 煤气","C 石油","D 天然气"},result=3},
[134]={question="有“钢琴诗人”之称的是？",answer={"A 贝多芬","B 莫扎特","C 肖邦","D 柴可夫斯基"},result=3},
[135]={question="有“风车之国”之称的国家是？",answer={"A 荷兰","B 丹麦"},result=1},
[136]={question="有“大自然的总调度室”之称的是？",answer={"A 矿产资源","B 水资源","C 森林资源","D 太阳能"},result=3},
[137]={question="油画《最后的晚餐》的作者是谁？",answer={"A 拉斐尔","B 梵高","C 达芬奇"},result=3},
[138]={question="由成语“墙头马上”的原意可知，元朝白朴所著的《墙头马上》属于什么类型的杂剧？",answer={"A 武侠","B 言情","C 伦理","D 历史"},result=2},
[139]={question="优盘和移动硬盘哪个体积大？",answer={"A 优盘","B 移动硬盘"},result=2},
[140]={question="用掌心或手背抚摸发烧者的前额测试发烧程度，哪一个更准确一些？",answer={"A 手背","B 手掌"},result=1},
[141]={question="用下列锅炒菜，对人体健康更有益的是：？",answer={"A 铝锅","B 铁锅"},result=2},
[142]={question="用微波炉煮荷包蛋时要用牙签在蛋清、蛋黄上扎孔主要是为了什么？",answer={"A 容易入味","B 防止爆裂","C 受热均匀","D 煮熟得快"},result=2},
[143]={question="用手机拨打110收不收费？",answer={"A 收","B 不收"},result=2},
[144]={question="用哪种水磨刀可使刀更快？",answer={"A 盐水","B 醋水"},result=1},
[145]={question="萤火虫发出的光是什么光源？",answer={"A 冷光源","B 热光源"},result=1},
[146]={question="婴儿出生时啼哭意味着婴儿开始有？",answer={"A 呼吸","B 听觉","C 视觉","D 味觉"},result=1},
[147]={question="英语文化一词原意是指：",answer={"A 勤奋","B 耕作","C 用餐","D 小说"},result=2},
[148]={question="隐形飞机是指什么样的飞机？",answer={"A 肉眼看不见","B 飞行太高看不见","C 体积太小","D 雷达测不到"},result=4},
[149]={question="银杏属于什么种类水果？",answer={"A 仁果类","B 核果类","C 竖果类","D 复果类"},result=3},
[150]={question="银行自动柜员机的英文缩写是什么？",answer={"A AMT","B ATM"},result=2},
[151]={question="音乐之城是指好莱坞吗？",answer={"A 是","B 不是"},result=2},
[152]={question="音乐城在哪个国家？",answer={"A 澳大利亚","B 德国","C 奥地利","D 法国"},result=3},
[153]={question="意大利的比萨斜塔已有超过多少年的历史？",answer={"A 600年","B 800后"},result=1},
[154]={question="艺术的目的就是显了人类的自由和进步是贝多芬说的吗？",answer={"A 是","B 不是"},result=1},
[155]={question="以郁金香而闻名世界的“欧洲花园”是？",answer={"A 英国","B 法国","C 荷兰"},result=3},
[156]={question="以下内容最能够反映英国发动鸦片战争本质意图的是？",answer={"A 割香港岛给英国","B 协定关税","C 领事裁判权","D 赔款2100万元"},result=1},
[157]={question="以下哪座塔是斜塔？",answer={"A 杭州六合塔","B 苏州虎丘塔","C 西安大雁塔","D 洛阳白马寺塔"},result=2},
[158]={question="以下哪种作物原产于我国？",answer={"A 玉米","B 荔枝","C 芝麻","D 辣椒"},result=2},
[159]={question="以下哪种食品不适于小儿冬季补益？",answer={"A 山楂","B 红小豆","C 茯苓","D 何首乌"},result=4},
[160]={question="以下哪种动物是软体动物？",answer={"A 蜗牛","B 蚕","C 变形虫","D 水蛭"},result=1},
[161]={question="以下哪一种商品的需求价格弹性最小？",answer={"A 食品","B 医药","C 电脑","D 书"},result=1},
[162]={question="以下哪一位曾被称为“药王”？",answer={"A 孙思邈","B 张仲景","C 李时珍","D 扁鹊"},result=1},
[163]={question="以下哪一位是中西交往史上较早的人物？",answer={"A 郑和","B 玄奘","C 苏武"},result=2},
[164]={question="以下哪一类茶是半发酵茶？",answer={"A 绿茶","B 红茶","C 乌龙茶"},result=3},
[165]={question="以下哪一个不是人名而是剑的名？",answer={"A 蔡愉","B 豫让","C 龙阳"},result=1},
[166]={question="以下哪些果实是核果？",answer={"A 樱桃","B 葡萄","C 石榴"},result=1},
[167]={question="以下哪位是中国历史上惟一一位的女皇帝（　）？",answer={"A 武则天","B 慈喜","C 孝庄","D 文成"},result=1},
[168]={question="以下哪个在四川？",answer={"A 玉门关","B 娘子关","C 剑门关","D 虎牢关"},result=3},
[169]={question="以下哪个省是大熊猫的产地？",answer={"A 湖南","B 甘肃","C 湖北","D 贵州"},result=2},
[170]={question="以下哪个技能使用后不会消耗魔法值",answer={"A 烈火剑法","B 刺杀剑术","C 突斩"},result=2},
[171]={question="以下哪个城市与白蛇传故事有关？",answer={"A 杭州","B 扬州"},result=1},
[172]={question="以下哪个不是杭州的景点？",answer={"A 虎跑泉","B 六和塔","C 沧浪亭","D 孤山"},result=3},
[173]={question="以下哪部戏剧的作者是明朝人？",answer={"A 《汉宫秋》","B 《赵氏孤儿》","C 《娇红记》","D 《精忠谱》"},result=3},
[174]={question="以下哪柄剑曾经为吴王所有？",answer={"A 泰阿","B 龙泉","C 磐郢"},result=3},
[175]={question="以下哪柄剑因为屡杀害忠臣而被视为不祥？",answer={"A 鱼肠","B 属镂","C 卫夫人匕首"},result=2},
[176]={question="以下哪柄剑不是大剑师欧冶子锻造的？",answer={"A 燕支","B 龙渊","C 工布"},result=1},
[177]={question="以下哪柄古剑不是秦人所铸？",answer={"A 水心","B 秀霸","C 定秦"},result=2},
[178]={question="以下哪把剑身是黑色的？",answer={"A 墨阳","B 鱼肠","C 湛卢"},result=3},
[179]={question="以下哪把宝剑铸成的时间最早？",answer={"A 龙泉","B 腾空","C 轩辕"},result=2},
[180]={question="以下节气中哪一个反映了自然界生物的物候现象？",answer={"A 春分","B 惊蛰","C 冬至","D 夏至"},result=2},
[181]={question="依照西方习俗,订婚戒指戴在左手哪根手指上？",answer={"A 食指","B 中指","C 无名指","D 小指"},result=3},
[182]={question="依照我国《未成年人保护法》规定，未成年人有隐私权吗？",answer={"A 有","B 没有"},result=1},
[183]={question="依照我国《民法通则》规定，未成年人的父母是未成年人的法定监护人吗？",answer={"A 是","B 不是"},result=1},
[184]={question="依照我国《婚姻法》规定，子女只能随父姓，不能随母姓吗？",answer={"A 是","B 不是"},result=2},
[185]={question="依照我国《婚姻法》规定，如果现役军人的配偶要求离婚，是否需要军人同意？",answer={"A 是","B 不是"},result=1},
[186]={question="依照我国《城市房地产管理法》规定，权属有争议的房屋可以转让吗？",answer={"A 可以","B 不可以"},result=2},
[187]={question="衣服在水中的浸泡时间越长就越易洗干净，对吗？",answer={"A 对","B 不对"},result=2},
[188]={question="一张女排的球网有多高？",answer={"A 2.15m","B 2.34m","C 2.24m","D 2.25m"},result=3},
[189]={question="一战持续的时间是：（）。",answer={"A 二年多","B 三年多","C 四年多","D 五年多"},result=3},
[190]={question="一日不见，如隔三秋里的“三秋”是指？",answer={"A 三个秋天","B 三个季度","C 三个月","D 三年"},result=4},
[191]={question="一千克铁和一千克木头哪个重？",answer={"A 木头","B 铁","C 一样重","D 没有可比性"},result=3},
[192]={question="一年有几个节气？",answer={"A 12","B 16","C 18","D 24"},result=4},
[193]={question="一九七九年，那是一个春天，有一位老人在中国的南海边画了一个圈------，“春天”的含义是？",answer={"A 改革开放","B 科教兴国","C 文革结束","D 包产到户"},result=1},
[194]={question="一个小姑娘，住在清水塘，穿件粉红衫，做在绿船上。(打一植物)",answer={"A 香蒲","B 水仙","C 凤眼莲","D 荷花"},result=4},
[195]={question="一朵向日葵花能结多少葵花籽？",answer={"A 成百上千个","B 一个","C 五个","D 五十个左右"},result=2},
[196]={question="一般说，同一只手上哪个手指的指甲生长得最快？",answer={"A 食指","B 小指","C 中指","D 无名指"},result=3},
[197]={question="一般来说，在发生通货膨胀时，靠固定工资生活的人：",answer={"A 生活水平会下降","B 生活水平会提高"},result=1},
[198]={question="夜阑卧听风吹雨的下一句是？",answer={"A 铁马冰河入梦来","B 僵卧孤村不自衰","C 尚思为国戍轮台"},result=1},
[199]={question="夜儿个：",answer={"A 月亮","B 昨天","C 身高","D 黑"},result=4},
[200]={question="叶子寿命最长的植物是千岁兰，它的叶子能够存活多少年而从不凋谢？",answer={"A 10年","B 100年","C 1000年","D 500年"},result=2},
[201]={question="仰韶文化是我国历史上哪个时代中期的文化？",answer={"A 旧石器","B 新石器","C 青铜器","D 铁器"},result=2},
[202]={question="阳春白雪和下里巴人源于什么时代？",answer={"A 春秋","B 战国","C 秦代","D 唐代"},result=2},
[203]={question="羊肉泡馍是我国哪一城市的风味食品？",answer={"A 北京","B 湖南","C 西安"},result=3},
[204]={question="盐水的沸点高还是清水的沸点高？",answer={"A 盐水","B 清水"},result=1},
[205]={question="亚洲首次举办奥运会是哪一届？",answer={"A 16届","B 17届","C 18届","D 19届"},result=3},
[206]={question="亚洲地势的特点是？",answer={"A 南高北低","B 西高东低","C 中高周低","D 东高西低"},result=3},
[207]={question="亚欧大陆桥欧洲的终点站是：",answer={"A 鹿特丹","B 阿姆斯特丹"},result=1},
[208]={question="血液中的红细胞可以活多久？",answer={"A 7天","B 120天","C 一生","D 80天"},result=2},
[209]={question="血管破裂时，血液中的什么物质会凝结成块，堵住破裂部分以止血？",answer={"A 红血球","B 白血球","C 血小板","D 血清"},result=3},
[210]={question="选出“欠儿登”的同义词",answer={"A 有债务","B 哪儿有事哪儿到","C 有债权","D 牛"},result=2},
[211]={question="选出“吭呲瘪肚”的同义词",answer={"A IQ高","B IQ低","C 速度快","D 速度慢"},result=4},
[212]={question="轩辕剑和仙剑是同一家游戏公司出品的吗？",answer={"A 是","B 不是"},result=1},
[213]={question="徐霞客是什么时代的旅行家？",answer={"A 明","B 清","C 唐","D 宋"},result=1},
[214]={question="徐悲鸿以画什么闻名世界？",answer={"A 奔马","B 虾"},result=1},
[215]={question="形容动物的鸣叫常用一个字表示，狼的叫声应该用：",answer={"A 啸","B 嗥","C 嘶","D 鸣"},result=2},
[216]={question="新四军是哪一地区抗日的主力？",answer={"A 华北","B 华东","C 华南","D 华中"},result=4},
[217]={question="心比天高，身为下贱是《红楼梦》中对谁的判词？",answer={"A 王熙凤","B 睛雯","C 薛宝钗"},result=2},
[218]={question="写下中国《二泉映月》的民间世人阿丙先生是哪里人？",answer={"A 江苏常州人","B 安徽芜湖人","C 江苏无锡人"},result=3},
[219]={question="校园歌曲《童年》的词曲作者是：",answer={"A 黄舒骏","B 李宗盛","C 罗大佑","D 李泰祥"},result=3},
[220]={question="小说羊脂球的作者是？",answer={"A 契科夫","B 屠格列夫","C 莫泊桑","D 欧亨利"},result=3},
[221]={question="小说《沉沦》是谁的作品？",answer={"A 矛盾","B 郁达夫","C 郭沫若","D 老舍"},result=2},
[222]={question="小荷才露尖尖角的下一句是？",answer={"A 泉眼无声惜细流","B 树阴照水爱睛柔","C 早有蜻蜓立上头"},result=3},
[223]={question="小儿生长发育最快的时期是：",answer={"A 新生儿期","B 婴儿期","C 幼儿期","D 学龄前期"},result=2},
[224]={question="小儿没爬就会走了，好吗？",answer={"A 好","B 不好"},result=2},
[225]={question="消防队救火：",answer={"A 收费","B 不收费","C 收取部分费用"},result=2},
[226]={question="向不在服务区的手机发送短信是否有效？",answer={"A 有效","B 无效"},result=1},
[227]={question="香港特别行政区的区花是？",answer={"A 菊花","B 月季","C 紫荆花"},result=3},
[228]={question="香港回归祖国的时间是？",answer={"A 1996.7","B 1997.7","C 1998.12","D 1999.12"},result=2},
[229]={question="相传我国古代能作“掌上舞”的人是：",answer={"A 杨玉环","B 赵飞燕","C 西施","D 貂蝉"},result=2},
[230]={question="现在世界上最大的城市是哪个？",answer={"A 东京","B 武汉","C 纽约","D 伦敦"},result=2},
[231]={question="现在美国国旗星条旗上有多少颗星？",answer={"A 25","B 30","C 50","D 60"},result=3},
[232]={question="鲜啤酒就是通常所说的？",answer={"A 生啤酒","B 熟啤酒"},result=2},
[233]={question="先天下之忧而忧，后天下之乐而乐出自（）的文章？",answer={"A 文天祥","B 辛弃疾","C 范仲淹"},result=3},
[234]={question="先天下之忧而忧，后天下之乐而乐。请问这句格言的作者是谁？",answer={"A 易经","B 李商隐","C 荀况","D 范仲淹"},result=4},
[235]={question="仙人掌原产？",answer={"A 雨林","B 高山","C 沙漠","D 湿地"},result=3},
[236]={question="下雪的时候为什么安静？",answer={"A 雪能吸收声音","B 雪能阻碍声音的传播","C 是听觉的错觉","D 雪能使之相应抵消"},result=1},
[237]={question="下面四种珍珠哪一种最珍贵？",answer={"A 天然淡水珠","B 淡水养殖珠","C 海水养殖珠","D 天然海水珠"},result=4},
[238]={question="下面哪种酸，人在品尝时不是酸味的？",answer={"A 琥珀酸","B 苹果酸","C 柠檬酸","D 单宁酸"},result=4},
[239]={question="下面哪种炊具对人体健康最有益？",answer={"A 不锈钢锅","B 铁锅","C 铝锅","D 沙锅"},result=2},
[240]={question="下面哪一种是能降血压的蔬菜？",answer={"A 白菜","B 芹菜","C 胡萝卜","D 茄子"},result=2},
[241]={question="下面哪个人物没有出现在《射雕英雄传》中（）。",answer={"A 郭靖","B 黄蓉","C 老顽童","D 令狐冲"},result=4},
[242]={question="下面几种水饮用后对人体都是有益的，但其中的哪种水是无法人工制造的？",answer={"A 天然矿泉水","B 活性水","C 过滤水"},result=1},
[243]={question="下面干果中脂肪含量最高的是？",answer={"A 板栗","B 皂角","C 核桃仁"},result=3},
[244]={question="下令“破釜沉舟”的我国古代将领是：",answer={"A 项庄","B 项羽","C 刘邦","D 张良"},result=2},
[245]={question="下列作中哪部是巴金的作品？",answer={"A 《骆驼祥子》","B 《茶馆》","C 《家》","D 《四世同堂》"},result=3},
[246]={question="下列作家中，创作《激流三部曲》的是？",answer={"A 郭沫若","B 叶圣陶","C 老舍","D 巴金"},result=4},
[247]={question="下列著名宫殿哪个位于英国？",answer={"A 故宫","B 凡尔赛宫","C 白金汉宫","D 克里姆林宫"},result=3},
[248]={question="下列著名雕塑中哪一件是罗丹的作品？",answer={"A 掷铁饼者","B 大卫","C 思想者","D 维纳斯"},result=3},
[249]={question="下列属于哺乳动物的是？",answer={"A 恐龙","B 蝙蝠","C 文昌鱼","D 麻雀"},result=2},
[250]={question="下列植物哪个开白花？",answer={"A 马铃薯","B 黄瓜","C 丝瓜"},result=1},
[251]={question="下列植物常用扦播的是？",answer={"A 夹竹桃","B 桂花","C 石榴","D 月季"},result=4},
[252]={question="下列责任中，不属于民事责任的是：",answer={"A 返还财产","B 赔偿损失","C 排除妨碍","D 罚款"},result=4},
[253]={question="下列与唐太宗没有直接关系的是（）。",answer={"A 玄武门之变","B 贞观之治","C 开元盛世","D 晋阳起兵"},result=3},
[254]={question="下列音乐作品中，由柴可夫斯基作曲的是：",answer={"A 悲怆交响曲","B 月光奏鸣曲","C 四季","D 悲怆奏鸣曲"},result=1},
[255]={question="下列姓氏中，哪些原不是古代的官名？",answer={"A 欧阳","B 司马","C 上官","D 夏侯"},result=1},
[256]={question="下列行星中，卫星最多的是？",answer={"A 水星","B 地球","C 土星"},result=3},
[257]={question="下列天体中，距离地球最近的恒星是：",answer={"A 太阳","B 比邻星","C 月球"},result=1},
[258]={question="下列蔬菜中富含铁质营养的是？",answer={"A 大豆","B 白菜","C 土豆","D 菠菜"},result=4},
[259]={question="下列史学著作中论及当时统治者的是：",answer={"A 《史记》","B 《汉书》","C 《后汉书》","D 《资治通鉴》"},result=1},
[260]={question="下列山脉与三大高原都相接的是？",answer={"A 横断山脉","B 阴山山脉","C 祁连山脉","D 秦岭"},result=3},
[261]={question="下列人种的分布中，纯属人口迁移造成的是：",answer={"A 非洲白色人种","B 澳洲棕色人种","C 亚洲白色人种","D 美洲黑色人种"},result=4},
[262]={question="下列人名哪一个最不适合加儿化音？",answer={"A 谢霆锋","B 葛优","C 王志文","D 蔡明"},result=1},
[263]={question="下列鸟类中哪一种是候鸟？",answer={"A 麻雀","B 喜鹊","C 黄鹂","D 啄木鸟"},result=3},
[264]={question="下列能源属新能源的有？",answer={"A 石油","B 太阳能","C 天然气","D 水能"},result=2},
[265]={question="下列哪座山不属于我国四大佛山之一：",answer={"A 雁荡山","B 五台山","C 九华山","D 峨眉山"},result=1},
[266]={question="下列哪种人最适宜坚持慢跑？",answer={"A 肺病","B 肝病","C 心脏病"},result=3},
[267]={question="下列哪种动物是一种昆虫？",answer={"A 蜘蛛","B 跳蚤","C 蝎子","D 蜈蚣"},result=2},
[268]={question="下列哪一项不属于华表曾经具有的功能？",answer={"A 标示道路","B 发表意见","C 皇家建筑的标志","D 悬挂路灯"},result=4},
[269]={question="下列哪一位著名画家擅长画虎？",answer={"A 张大千","B 张善子","C 徐悲鸿","D 齐白石"},result=2},
[270]={question="下列哪一个城市是在1949.10建国后才解放的？",answer={"A 广州","B 上海","C 南京","D 西安"},result=1},
[271]={question="下列哪一个城市不是我国的“三大火炉”(高温)之一？",answer={"A 重庆","B 成都","C 武汉","D 南京"},result=2},
[272]={question="下列哪一个不是我国的领海？",answer={"A 黄海","B 东海","C 北海","D 渤海"},result=3},
[273]={question="下列哪项仅属国家所有？",answer={"A 煤矿","B 森林","C 00原","D 滩涂"},result=1},
[274]={question="下列哪位世界著名男高音哪位是意大利人？",answer={"A 盖达","B 帕瓦多蒂","C 多明戈","D 毕约林"},result=2},
[275]={question="下列哪个岛国不是欧洲国家？",answer={"A 爱尔兰","B 马尔代夫","C 马耳他","D 冰岛"},result=2},
[276]={question="下列哪次古代著名战役确立了三国鼎立局面？",answer={"A 官渡之战","B 赤壁之战","C 夷陵之战","D 长平之战"},result=2},
[277]={question="下列哪部小说是郁达夫先生的作品？",answer={"A 锻炼","B 南迁","C 子夜","D 寒冬"},result=2},
[278]={question="下列名著中，以动物为主人公的是？",answer={"A 《蝇王》","B 《我是猫》","C 《兔子，跑吧》","D 《猫与鼠》"},result=2},
[279]={question="下列名关哪一座被称为“天下第一关”？",answer={"A 居庸关","B 娘子关","C 潼门关","D 山海关"},result=4},
[280]={question="下列名称不属于二十四节气的是？",answer={"A 霜降","B 大雪","C 谷雨","D 大伏"},result=4},
[281]={question="下列老鼠的天敌中，哪一种是以老鼠为主食？",answer={"A 猫头鹰","B 狗","C 猫","D 啄木鸟"},result=1},
[282]={question="下列可以概括唐与吐蕃关系的词句是（）。",answer={"A 唐风洋溢奈良城","B 车书本一家","C 和同为一家　","D 和同开"},result=3},
[283]={question="下列科学家中，为我国的石油工业发展做出重大贡献的是（）。",answer={"A 李四光","B 华佗","C 侯德榜","D 牛顿"},result=1},
[284]={question="下列河流哪一条是世界流程最长？",answer={"A 尼罗河","B 长江","C 亚马孙河","D 密西西比河"},result=1},
[285]={question="下列官名中那个不是唐朝的官名？",answer={"A 尚书","B 黄门","C 巡按","D 殿中"},result=4},
[286]={question="下列古都哪个被称为“六朝古都”？",answer={"A 洛阳","B 西安","C 南京","D 北京"},result=3},
[287]={question="下列各朝代疆域西至最远的是：",answer={"A 秦朝","B 唐朝","C 宋朝","D 清朝"},result=2},
[288]={question="下列对围棋的表述正确的是？",answer={"A 执黑者先走","B 执白者先走"},result=1},
[289]={question="下列城市中，为著名文化古城欧洲文艺复兴运动发源地的是（）。",answer={"A 维也纳","B 佛罗伦萨","C 马德里","D 圣彼得堡"},result=2},
[290]={question="下列不属于我国西部大开发的省份是：",answer={"A 青海","B 陕西","C 新疆","D 山西"},result=4},
[291]={question="下列4种存储器中，存取周期最短的是哪个？",answer={"A 硬盘存储器","B 光盘存储器","C 内存储器","D 软盘存储器"},result=3},
[292]={question="下半旗致哀，这一礼节源自？",answer={"A 英国","B 法国"},result=1},
[293]={question="下半旗是把旗子下降到：",answer={"A 旗杆的一半处","B 下降1米","C 下降1.5米","D 距离杆顶的1／3处"},result=4},
[294]={question="瞎子阿炳是中国民间艺人华彦钧的小名，对吗？",answer={"A 对","B 不对"},result=1},
[295]={question="洗头发时加醋使头发更光亮吗？",answer={"A 对","B 不对"},result=1},
[296]={question="蟋蟀的“耳朵”长在：",answer={"A 头顶上","B 前足的小腿节上","C 触须上","D 翅膀上"},result=2},
[297]={question="吸烟有害，烟草中毒性最大的物质是哪个？",answer={"A 烟焦油","B 亚硝胺","C 砷","D 烟碱"},result=4},
[298]={question="西装袖口上的钮扣是因何而被钉上的？",answer={"A 保持衣报整洁","B 体现主人等级","C 为了装饰衣服"},result=1},
[299]={question="西游记中去西天取经的“唐三藏”真名叫什么？",answer={"A 玄慈","B 玄明","C 唐僧","D 玄奘"},result=4},
[300]={question="勿以恶小而为之，勿以善小而不为。惟贤惟德，能服于人。请问这句格言的作者是谁？",answer={"A 诸葛亮","B 朱熹","C 刘备","D 墨翟"},result=3},
[301]={question="舞蛇者表演时，蛇随舞蛇者舞动是因为？",answer={"A 音乐的影响","B 舞蛇者动作的影响"},result=2},
[302]={question="武则天时在西突厥地区设立的机构是（）。",answer={"A 安西都护府　","B 北庭都护府　　","C 西域都护府　","D 辽阳都护府"},result=2},
[303]={question="武则天的陵墓在西安附近的什么地方？",answer={"A 茂陵","B 黄陵","C 乾陵","D 西陵"},result=3},
[304]={question="五子棋段位制最高为：",answer={"A 一段","B 六","C 九段","D 十二段"},result=3},
[305]={question="五岳之中位于陕西的是？",answer={"A 东岳","B 南岳","C 西岳","D 中岳"},result=4},
[306]={question="五一成为全世界无产阶级和劳动人民节日的时间是：（）。",answer={"A 1848.2","B 1864.9","C 1871.3","D 1889.7"},result=4},
[307]={question="五香除花椒、茴香子外还有包括什么？",answer={"A 八角、辣椒、丁香","B 八角、桂皮、丁香花蕾","C 桂皮、六角、胡椒","D 芥末、桂皮、八角"},result=2},
[308]={question="五谷中的‘菽’是指什么？",answer={"A 谷子","B 大豆","C 玉米","D 高梁"},result=2},
[309]={question="五大淡水湖中面积最大的是？",answer={"A 洞庭湖","B 鄱阳湖"},result=2},
[310]={question="吴某的邻居盖房，吴某主动相帮，不慎被砸伤。请问，依照我国《民法通则》规定，吴某可以要求邻居分担医疗费吗？",answer={"A 可以","B 不可以"},result=1},
[311]={question="吴敬梓是哪本名著的作者？",answer={"A 儒林外传","B 儒林传奇","C 儒林外史"},result=3},
[312]={question="无水酒精可以用来清洗电脑显示器吗？`？",answer={"A 能","B 不能"},result=2},
[313]={question="无风杨柳漫天絮的下一句是？",answer={"A 碧瓦楼前乡幕遮","B 不雨海棠满地花","C 赤栏桥外绿溪斜"},result=2},
[314]={question="我们所穿的衣服每天把成千上万个表皮细胞揩掉。人们每过多少天就换上一层新的表皮？",answer={"A 15天","B 20天","C 27天","D 31天"},result=3},
[315]={question="我们日常的主食基本上属于什么食物？",answer={"A 酸性食物","B 碱性食物","C 中性食物","D 半酸半碱食物"},result=1},
[316]={question="我们日常吃的紫菜属于下列哪种藻类？",answer={"A 红藻","B 褐藻","C 绿藻","D 黄藻"},result=1},
[317]={question="我们的鼻子有多少个嗅觉感受器？",answer={"A 300万","B 50万","C 500万","D 800万"},result=3},
[318]={question="我们白天看到的太阳是太阳的什么？",answer={"A 光球层","B 色球层","C 平流层","D 日冕"},result=1},
[319]={question="我国最早的字典是？",answer={"A 《说文解字》","B 《康熙字典》","C 《辞海》"},result=3},
[320]={question="我国最早的佛寺是？",answer={"A 少林寺","B 白马寺","C 灵隐寺"},result=2},
[321]={question="我国最先出现的纸币是：",answer={"A 元代的“宝钞”","B 元代的“交子”","C 宋代的“宝钞”","D 宋代的“交子”"},result=4},
[322]={question="我国最大的瀑布“黄果树瀑布”位于哪个省？",answer={"A 湖南","B 贵州","C 四川","D 江西"},result=2},
[323]={question="我国最大的内陆咸水湖是？",answer={"A 洪泽湖","B 太湖","C 鄱阳湖","D 青海湖"},result=4},
[324]={question="我国著名的六朝古都是？",answer={"A 北京","B 西安","C 南京"},result=3},
[325]={question="我国著名的本草著作《本草纲目》（作者：李时珍）创作于哪个朝代？",answer={"A 唐朝","B 宋朝","C 元朝","D 明朝"},result=4},
[326]={question="我国有一个专门进行核试验的“原子城”,它位于？",answer={"A 新疆","B 西藏","C 四川","D 青海"},result=3},
[327]={question="我国姓氏中哪一个姓氏的人口比例最多？",answer={"A 王","B 李","C 张","D 刘"},result=2},
[328]={question="我国现存最早的兵书是：？",answer={"A 《孙膑兵法》","B 《吴子》","C 《孙子兵法》","D 《六韬》"},result=3},
[329]={question="我国西晋的第一代皇帝名叫？",answer={"A 曹丕","B 司马睿","C 司马炎","D 司马懿"},result=3},
[330]={question="我国台湾省的居民中，人口最多的民族是？",answer={"A 高山族","B 京族","C 黎族","D 汉族"},result=4},
[331]={question="我国四大名亭中哪一座亭名是毛泽东题的？",answer={"A 爱晚亭","B 醉翁亭","C 陶然亭","D 湖心亭"},result=1},
[332]={question="我国水能资源最丰富的河流是？",answer={"A 珠江","B 长江","C 黄河","D 松花江"},result=2},
[333]={question="我国是从哪个朝代开始制作香水的？",answer={"A 唐朝","B 宋朝","C 元朝"},result=1},
[334]={question="我国世界遗产数量在世界排列第几？",answer={"A 第一","B 第二","C 第三","D 第四"},result=3},
[335]={question="我国十二生肖纪年法中蒙古族与维吾尔族所用十二生肖一样吗？",answer={"A 一样","B 不一样"},result=2},
[336]={question="我国盛产茶花的城市是：",answer={"A 长沙","B 成都","C 昆明","D 大理"},result=4},
[337]={question="我国少数民族分布最多的省份是？",answer={"A 广西","B 西藏","C 云南","D 四川"},result=3},
[338]={question="我国人民解放军第一位女将军是：？",answer={"A 李贞","B 贺子珍","C 邓颖超","D 蔡畅"},result=1},
[339]={question="我国曲艺中的相声是：",answer={"A 北方曲种","B 南方曲种"},result=1},
[340]={question="我国清代伟大的现实主义作家是（）。",answer={"A 侯方域","B 蒲松龄","C 曹雪芹","D 顾炎武"},result=3},
[341]={question="我国哪座名山经常出现猴子向游人索要食物的情况？",answer={"A 峨嵋山","B 庐山"},result=1},
[342]={question="我国哪种茶被英国人称之为“茶中英豪”？",answer={"A 祁门红茶","B 西湖龙井茶","C 黄山毛峰"},result=1},
[343]={question="我国哪个省级行政单位的省区最多？",answer={"A 上海","B 北京","C 内蒙古自治区","D 新疆"},result=3},
[344]={question="我国历史上最早的一部兵书是指（）。",answer={"A 《孙膑兵法》","B 《孙子兵法》","C 《老子》","D 《易经》"},result=2},
[345]={question="我国历史上规模最大的水战是哪次战役？",answer={"A 元末鄱阳湖大战","B 官渡之战","C 赤壁之战","D 淝水之战"},result=1},
[346]={question="我国家用电器使用的是？",answer={"A 交流电","B 直流电"},result=1},
[347]={question="我国古代有人口统计机构吗？",answer={"A 有","B 没有"},result=1},
[348]={question="我国古代文学名作《桃花源诗》和诗序《桃花源记》的作者是（）。",answer={"A 屈原，陶渊明","B 陶渊明，陶渊明","C 杜甫，李白","D 陆游，苏轼"},result=2},
[349]={question="我国古代图书一般分为经、史、子、集四大类，诗词作品归于哪一类？",answer={"A 经","B 史","C 子","D 集"},result=4},
[350]={question="我国古代人物形象最多的小说是？",answer={"A 《红楼梦》","B 《水浒传》","C 《三国演义》"},result=1},
[351]={question="我国古代哪位文学家曾两度到杭州做官？",answer={"A 欧阳修","B 杜甫","C 白居易","D 苏轼"},result=4},
[352]={question="我国古代称生什么为“弄瓦”？",answer={"A 男孩","B 女孩","C 第一个孩子","D 第二个孩子"},result=2},
[353]={question="我国古代《二十四史》的第一部是？",answer={"A 史记","B 左传","C 春秋","D 汉书"},result=1},
[354]={question="我国古代“三十六计”中第36计是：？",answer={"A 美人计","B 空城计","C 走为上计","D 反间计"},result=3},
[355]={question="我国公安机关的性质是？",answer={"A 行政机关","B 派出机关","C 立法机关"},result=1},
[356]={question="我国法律承认双重国籍吗？",answer={"A 承认","B 不承认"},result=2},
[357]={question="我国第一座自行设计、自行建造的核电站是哪一个？",answer={"A 秦山核电站","B 大亚湾核电站"},result=1},
[358]={question="我国第一座地热发电站是？",answer={"A 羊六井","B 羊八井","C 羊三井"},result=2},
[359]={question="我国第一个国家森林公园是？",answer={"A 九寨沟","B 武夷山","C 张家界"},result=3},
[360]={question="我国第一部在国际电影节上获奖的影片是？",answer={"A 《定军山》","B 《渔光曲》","C 《祝福》","D 《红高梁》"},result=2},
[361]={question="我国第一部以农民起义为题材的长篇小说是（）。",answer={"A 《水浒传》","B 《西游记》","C 《三国演义》","D 《红楼梦》"},result=1},
[362]={question="我国第一部纪传体通史《史记》共几篇？",answer={"A 200篇","B 130篇","C 175篇"},result=2},
[363]={question="我国的夜市最早出现在？",answer={"A 汉朝","B 唐朝","C 宋朝"},result=2},
[364]={question="我国的哪一个城市素有“日光之城”的美称？",answer={"A 厦门","B 青岛","C 三亚","D 拉萨"},result=4},
[365]={question="我国的几何中心是：",answer={"A 西宁","B 兰州","C 北京","D 开封"},result=2},
[366]={question="我国的海岸线有多少公里？",answer={"A 17000","B 18000","C 19000","D 20000"},result=2},
[367]={question="我国的根本大法是什么法？",answer={"A 宪法","B 刑法"},result=1},
[368]={question="我国的第一部诗歌总集是？",answer={"A 楚辞","B 乐府","C 诗经","D 春秋"},result=3},
[369]={question="凤姐真实名字是什么",answer={"A 罗玉凤","B 罗凤","C 罗美凤","D 罗飞凤"},result=1},
[370]={question="我国的“冰城”是指哪一城市？",answer={"A 吉林市","B 哈尔滨","C 辽阳市","D 牡丹江"},result=2},
[371]={question="我国从什么时候起就有了历法？",answer={"A 汉","B 商","C 周","D 夏"},result=4},
[372]={question="我国被称为“不夜城”的是哪一城市？",answer={"A 漠河","B 齐齐哈尔"},result=1},
[373]={question="问仓储超市与其它超市最大的不同点是什么？",answer={"A 铺房简陋","B 储售场地合一"},result=2},
[374]={question="蚊子发出的“嗡嗡”的声音是由于？",answer={"A 鸣叫","B 翅膀振动"},result=2},
[375]={question="蚊虫叮咬也可以传播艾滋病病毒，对不对？",answer={"A 对","B 不对"},result=2},
[376]={question="文艺复兴时期的美术创作，是否已运用黄金分割律？",answer={"A 是","B 不是"},result=1},
[377]={question="文学一词最早是指官职吗？",answer={"A 是","B 不是"},result=1},
[378]={question="文学史上魔幻现实主义流派的代表人物是：",answer={"A 卡夫卡","B 扎米亚京","C 马尔克斯"},result=3},
[379]={question="文学名篇《人变兽》的作者是哪一位作家？",answer={"A 鲁迅","B 矛盾","C 闻一多","D 徐志摩"},result=4},
[380]={question="文过饰非中“文”是指？",answer={"A 做文章","B 掩饰","C 听，同闻"},result=2},
[381]={question="温故而知新，可以为师矣出自（）。",answer={"A 论语","B 庄子","C 礼记"},result=1},
[382]={question="位于云冈石窟附近的大型煤矿是？",answer={"A 平顶山","B 兖州","C 大同","D 淮北"},result=3},
[383]={question="位于欧洲的世界著名的鱼场是？",answer={"A 北海渔场","B 北海道渔场","C 秘鲁渔场","D 纽芬兰渔场"},result=4},
[384]={question="委托人所确定的拍卖标的的保留价是成交的最高价吗？",answer={"A 是","B 不是"},result=2},
[385]={question="伟大的文学家、革命家鲁迅先生逝世于哪一年？",answer={"A 1936","B 1937","C 1938","D 1939"},result=1},
[386]={question="为什么说“运动不宜饮酒”？",answer={"A 饮酒会兴奋","B 饮酒会降低运动员的运动能力"},result=2},
[387]={question="为什么呢？是谁的口头禅？",answer={"A 小沈阳","B 范伟"},result=1},
[388]={question="为什么国外称电视剧为肥皂剧？",answer={"A 泡沫太多","B 最初由肥皂商赞助的","C 情节太虚，无真实感"},result=2},
[389]={question="为了表演的需要，芭蕾鞋的鞋尖内赛有一小块？",answer={"A 海棉","B 木头","C 橡胶"},result=2},
[390]={question="微波炉可以空载运行吗？",answer={"A 可以","B 不可以"},result=2},
[391]={question="往已有脚臭味的鞋中喷什么可以除臭？",answer={"A 香水","B 醋","C 酒"},result=3},
[392]={question="王安石变法发生在宋朝哪个皇帝在位期间？",answer={"A 仁宗","B 神宗","C 哲宗","D 高宗"},result=2},
[393]={question="亡羊补牢中的“牢”指的是？",answer={"A 牢房","B 牲口圈","C 院子","D 栅栏"},result=2},
[394]={question="玩桥牌时，首局由哪家开始叫牌？",answer={"A 东家","B 南家","C 西家","D 北家"},result=4},
[395]={question="外籍车号牌的颜色是？",answer={"A 黄底黑字符","B 蓝底白字符","C 黑底白字符"},result=3},
[396]={question="鸵鸟遇到惊吓或敌害时可能会：",answer={"A 把头埋进沙子里","B 将脖子平贴地面","C 把全身埋进沙子里"},result=2},
[397]={question="兔子的长耳朵主要起什么作用？",answer={"A 集音功能","B 散发体热"},result=2},
[398]={question="土耳其的首都在？",answer={"A 华沙","B 安卡拉","C 安道尔"},result=2},
[399]={question="通常鱼在一年四季中什么时候长得最慢？",answer={"A 春天","B 夏天","C 秋天","D 冬天"},result=4},
[400]={question="通常所说的电脑游戏ACT是指？",answer={"A 角色扮演游戏","B 策略游戏","C 动作游戏","D 模拟游戏"},result=3},
[401]={question="通常情况下，中秋节晚上的月亮总是比第二天晚上的月亮亮吗？",answer={"A 是","B 不是"},result=2},
[402]={question="通常高级龙井茶的采制时间多在何时之前？",answer={"A 清明节","B 重阳节","C 谷雨","D 端午节"},result=3},
[403]={question="铁锅通常用哪种铁制成？",answer={"A 生铁","B 熟铁"},result=1},
[404]={question="铁达尼号游轮是哪一年沉没的？",answer={"A 1910年","B 1911年","C 1912年","D 1913年"},result=3},
[405]={question="挑选虾米时应挑选身体？",answer={"A 弯曲的","B 挺直的"},result=1},
[406]={question="天空上美丽的彩虹经常是在雨后出现的，是吗？",answer={"A 是","B 不是"},result=1},
[407]={question="天空上的星星为什么有的亮，有的暗？",answer={"A 大小不一样","B 发光能力不一样","C 方向不同","D 距离不同"},result=2},
[408]={question="天长地久有时尽，下面一句正确的是（）。",answer={"A 天上人间会相见","B 耿耿星河欲曙天","C 此恨绵绵无绝期","D 秋雨梧桐叶落时"},result=3},
[409]={question="提出著名的韦达公式的数学家韦达，是哪国人？",answer={"A 英国","B 法国","C 德国","D 俄国"},result=2},
[410]={question="唐时，深刻反映唐朝由盛转衰的历史，其诗后人称为“诗史”的诗人是？",answer={"A 李白","B 杜甫","C 白居易","D 王维"},result=2},
[411]={question="唐三彩主要是指哪三种色彩？",answer={"A 红黄绿","B 红蓝绿","C 黄绿白"},result=3},
[412]={question="唐高祖武德四年的开元通宝，开元所代表的意思为？",answer={"A 开辟新纪元","B 年号","C 道号"},result=1},
[413]={question="唐代“山水田园诗派”以哪些诗人为代表？",answer={"A 王昌龄、岑参","B 孟浩然、王维","C 岑参、王维","D 孟浩然、王昌龄"},result=2},
[414]={question="唐朝最著名的陶器是？",answer={"A 青瓷","B 白瓷","C 青花瓷","D 唐三彩"},result=4},
[415]={question="澳大利亚的国宝是什么动物？",answer={"A 袋鼠","B 鹰","C 熊猫","D 树袋熊"},result=1},
[416]={question="唐朝时期寓言故事“黔之驴”的作者是？",answer={"A 李白","B 杜甫","C 韩愈","D 柳宗元"},result=4},
[417]={question="唐朝时道教发展到极盛的皇帝是（）。",answer={"A 唐太宗","B 唐高宗","C 唐玄宗","D 武则天"},result=3},
[418]={question="唐朝时，被人们称为“诗仙”的诗人是？",answer={"A 李白","B 杜甫","C 白居易","D 王维"},result=1},
[419]={question="唐朝的开国皇帝是？",answer={"A 唐高祖","B 唐太宗","C 唐高宗","D 唐玄宗"},result=1},
[420]={question="昙花一现是“现”在？",answer={"A 早上","B 中午","C 晚上"},result=3},
[421]={question="泰国是世界上著名的佛教国，居民中信奉佛教的人不少于？",answer={"A 85%","B 90%"},result=2},
[422]={question="泰阿是欧冶子铸成的第几把宝剑？",answer={"A 3","B 1","C 2"},result=3},
[423]={question="太阳系中最大的行星是:",answer={"A 土星","B 木星","C 火星","D 海王星"},result=2},
[424]={question="太平天国中的东王是谁？",answer={"A 韦昌辉","B 冯云山","C 萧朝贵","D 杨秀清"},result=4},
[425]={question="台湾的最大城市、最大的海港是？",answer={"A 高雄","B 基隆","C 台北","D 台南"},result=1},
[426]={question="他盯把儿看我。该句子的意思是：",answer={"A 他盯着我","B 他恶狠狠地看我","C 他总看我","D 他深情地看着我"},result=1},
[427]={question="所有的植物都有种子？",answer={"A 对","B 不对"},result=2},
[428]={question="隋文帝是（）。",answer={"A 杨广","B 杨勇","C 杨坚","D 杨业"},result=2},
[429]={question="酸甜苦辣咸五味中唯一不是由味觉感受器官感觉引起的是？",answer={"A 酸","B 甜","C 苦","D 辣"},result=4},
[430]={question="酸牛奶和“乳酸牛奶”是同一类型的饮品吗？",answer={"A 是","B 不是"},result=2},
[431]={question="塑料袋通常用什么来制造？",answer={"A 聚苯乙烯","B 聚乙烯","C 聚氯乙烯","D 聚脂碳酸"},result=2},
[432]={question="素有“悬念大师”之称的著名导演是谁？",answer={"A 斯皮尔伯格","B 希区柯克"},result=2},
[433]={question="俗话说“五岳归来不看山”，哪里归来不看岳？",answer={"A 黄山","B 庐山"},result=1},
[434]={question="俗称的“黑管”是哪种木管乐器？",answer={"A 单簧管","B 双簧管","C 巴松"},result=1},
[435]={question="俗称“长生果”是指？",answer={"A 花生","B 腰果","C 核桃"},result=1},
[436]={question="送水节是柬埔寨最隆重的节日吗？",answer={"A 是","B 不是"},result=1},
[437]={question="宋朝文学的主要成就是：（）。",answer={"A 诗歌","B 散文","C 词","D 戏曲"},result=3},
[438]={question="宋朝为加强中央司法机构的控制，在皇宫中设立（）。",answer={"A 大司徙","B 审刑院","C 大理院","D 《宣政院》"},result=2},
[439]={question="松纹最早是以下哪把剑别称？",answer={"A 青虹","B 莫邪","C 鱼肠"},result=3},
[440]={question="四大名亭中的陶然亭是因为谁的诗句得名的？",answer={"A 欧阳修","B 白居易","C 陶渊明","D 杜牧"},result=2},
[441]={question="___的建立被列为中国文联98年十件实事之一？",answer={"A 中国互联网","B 中国文娱网","C 中国娱乐网","D 中国金桥网"},result=2},
[442]={question="四大美女中为汉匈友好作出了贡献的是（）。",answer={"A 西施","B 貂蝉","C 王昭君","D 杨玉环"},result=3},
[443]={question="四川现在是我国人口最多的省吗？",answer={"A 是","B 不是"},result=2},
[444]={question="四川乐山大佛开凿了多少年？",answer={"A 50年","B 90年"},result=2},
[445]={question="水族姑娘出嫁后要完成的第一件事是：",answer={"A 挑柴","B 挑水","C 挑米"},result=2},
[446]={question="水在摄氏多少度时密度最大？",answer={"A 零下10度","B 0度","C 4度","D 10度"},result=3},
[447]={question="水调歌头明月几时有，把酒问青天。不知天上宫阙，今夕是何年。作者是？",answer={"A 杜牧","B 温庭筠","C 卢纶","D 苏轼"},result=4},
[448]={question="水波不兴(打一中国地名)",answer={"A 普宁","B 湘潭","C 平湖","D 汨罗"},result=3},
[449]={question="双喜临门是我国哪个省市的名字？",answer={"A 南京","B 北京","C 天津","D 重庆"},result=4},
[450]={question="涮羊肉起源于？",answer={"A 清朝","B 元朝"},result=2},
[451]={question="树木的水分主要从哪个部位流失？",answer={"A 树叶","B 树皮","C 枝条"},result=1},
[452]={question="树的年轮密集的方向是？",answer={"A 背阳的方向","B 向阳的方向"},result=2},
[453]={question="树的年轮的形成和下列哪项条件有直接关系？",answer={"A 雨水","B 温度","C 地势","D 阳光"},result=1},
[454]={question="书圣王羲之的代表作是《兰亭序》吗？",answer={"A 是","B 不是"},result=1},
[455]={question="书画作品中的“四君子”是指梅、牡丹、竹、菊吗？",answer={"A 是","B 不是"},result=2},
[456]={question="手绢是由什么演变而来的？",answer={"A 肚兜","B 领带","C 头巾"},result=3},
[457]={question="是哪国人最先制作出了牛奶巧克力？",answer={"A 英国","B 西班牙","C 意大利","D 瑞士"},result=4},
[458]={question="世界足球之王贝利的球衣号为？",answer={"A 10","B 12","C 23","D 5"},result=1},
[459]={question="世界四大古文明发源地都位于大河流域？",answer={"A 对","B 不对"},result=1},
[460]={question="世界上最早使用石油和天然气的是中国吗？",answer={"A 是","B 不是"},result=1},
[461]={question="世界上最早记录火药制作方法的是谁？",answer={"A 孙思邈","B 沈括"},result=1},
[462]={question="世界上最早的有声片是《爵士歌王》吗？",answer={"A 是","B 不是"},result=1},
[463]={question="世界上最早的计时钟是？",answer={"A 水钟","B 机械钟","C 风钟"},result=1},
[464]={question="世界上最靠北的首都是？",answer={"A 斯德哥尔摩","B 莫斯科","C 雷克亚未克","D 哥本哈根"},result=3},
[465]={question="世界上最大的内陆国是？",answer={"A 蒙古","B 扎伊尔","C 哈萨克斯坦","D 乌克兰"},result=3},
[466]={question="世界上最大的宫殿是：",answer={"A 故宫","B 白宫","C 爱丽舍宫","D 克里姆林宫"},result=1},
[467]={question="世界上最大的动物是哪一种？",answer={"A 鲸鱼","B 水母","C 恐龙","D 大象"},result=2},
[468]={question="世界上最长的叙事诗是？",answer={"A 《伊利亚特》","B 《格萨尔王传》"},result=2},
[469]={question="世界上最长的万里长城的全长约？",answer={"A 6000公里","B 8000公里","C 1万公里"},result=1},
[470]={question="世界上最长的山脉是：",answer={"A 比利牛斯山","B 喜马拉雅山","C 安第斯山","D 乞力马扎罗山"},result=3},
[471]={question="世界上种植面积最大种植量最广泛的粮食作物是？",answer={"A 水稻","B 小麦","C 玉米","D 大豆"},result=2},
[472]={question="世界上以吃辣闻名的国家是哪个？",answer={"A 墨西哥","B 中国"},result=1},
[473]={question="世界上销售量最大的酒是？",answer={"A 黄酒","B 米酒","C 白酒","D 啤酒"},result=4},
[474]={question="世界上现存最大的佛教艺术宝库是？",answer={"A 敦煌石窟","B 云冈石窟","C 龙门石窟","D 大足石窟"},result=1},
[475]={question="世界上流经国家最多的河流是？",answer={"A 多瑙河","B 尼罗河","C 莱茵河","D 亚马逊河"},result=1},
[476]={question="世界上邻国最多的国家是？",answer={"A 中国","B 俄罗斯"},result=1},
[477]={question="世界上海岸线最曲折的是哪个大洲？",answer={"A 亚洲","B 北美洲","C 非洲","D 欧洲"},result=4},
[478]={question="世界上第一只手表是由哪个国家发明的？",answer={"A 瑞士","B 德国"},result=2},
[479]={question="世界上第一辆摩托车其主要材料是：",answer={"A 塑料","B 木头","C 铁皮"},result=2},
[480]={question="世界上第一颗爆炸的原子弹的名字是？",answer={"A 瘦子","B 胖子","C 男孩","D 女孩"},result=1},
[481]={question="世界上第一个发明麻醉手术的是扁鹊吗？",answer={"A 是","B 不是"},result=2},
[482]={question="世界名胜吴哥窟位于哪个国家？",answer={"A 柬埔寨","B 缅甸","C 老挝"},result=1},
[483]={question="世界“七大奇迹”之一的摩索拉斯陵墓的建造地点在哪个国家？",answer={"A 土耳其","B 马其顿","C 叙利亚"},result=1},
[484]={question="食色性也，是谁说的？",answer={"A 孔子","B 孟子"},result=2},
[485]={question="时代歌手聂耳是哪里人？",answer={"A 云南","B 四川","C 河南","D 山东"},result=1},
[486]={question="石英是一种常见的矿物，它的分子由一个硅原子和两个氧原子组成。这句话有语病是吗？",answer={"A 是","B 否"},result=2},
[487]={question="石头城是对我国哪座城市的美称？",answer={"A 南昌","B 南京","C 拉萨","D 西安"},result=2},
[488]={question="十岁以下的小娃娃就当了皇帝的，在中国历史上共有几个？",answer={"A 19位","B 22位","C 25位","D 29位"},result=4},
[489]={question="十年树木，百年树人出自谁的名言？",answer={"A 管仲","B 齐桓公孔子","C 唐高宗"},result=1},
[490]={question="十面埋伏发生在哪个历史时期？",answer={"A 七国争雄","B 楚汉相争","C 三国鼎立"},result=2},
[491]={question="十斤棉花比五千克的铁重量轻，是吗？",answer={"A 是","B 不是"},result=2},
[492]={question="施毒术是道士成长过程中第几个学会的技能",answer={"A 4","B 3","C 2"},result=2},
[493]={question="诗仙李白的诗作风格豪迈，气势磅礴，名句“飞流直下三千尺，疑是银河落九天”出自他的",answer={"A 是","B 不是"},result=1},
[494]={question="诗人李白曾云：“江水水清清如许”。请问这句诗所赞美的江是什么江？",answer={"A 钱塘江","B 漓江","C 鸭绿江"},result=1},
[495]={question="诗名“蓦然回首，那人却在灯火栏栅处”出自哪个诗人？",answer={"A 李清照","B 杜甫","C 辛弃疾","D 李白"},result=3},
[496]={question="诗句“落花时节又逢君”中的“君”指的是：",answer={"A 李白","B 杜甫","C 李商隐","D 李龟年"},result=4},
[497]={question="诗集《女神》的作者是？",answer={"A 闻一多","B 戴望舒","C 郭沫若","D 冰心"},result=3},
[498]={question="诗鬼是？",answer={"A 李白","B 李贺","C 李商隐","D 贾岛"},result=2},
[499]={question="诗《春思》是（　）的作品？",answer={"A 李白","B 令狐冲","C 杜牧","D 任盈盈"},result=1},
[500]={question="诗《出塞》“秦时明月汉时关，万里长征人未还。但使龙城飞将在，不教胡马渡阴山。”的作者是（）。",answer={"A 王菲","B 王昌龄","C 王大维","D 王王"},result=2},
[501]={question="声音在哪里传播更快？",answer={"A 空气中","B 水中"},result=2},
[502]={question="生物体进行生命活动的能量，究其根源都来自太阳光能，是吗？",answer={"A 是","B 不是"},result=1},
[503]={question="生日吃长寿面的习俗由来？",answer={"A 面条在古代是珍贵食品","B 与相面术有关"},result=2},
[504]={question="生吃萝卜对身体有益吗？",answer={"A 没有","B 有"},result=2},
[505]={question="蜃楼疑海上，鸟道没云中赞美的是？",answer={"A 悬空寺","B 白云寺","C 白马寺","D 少林寺"},result=1},
[506]={question="设计出内燃机的是：（）。",answer={"A 卡尔·苯次","B 莫尔斯","C 爱迪生","D 福特"},result=1},
[507]={question="冰冻项链的战力是多少？",answer={"A 28888","B 288888","C 2888888"},result=2},
[508]={question="少林寺位于五岳中的哪一岳？",answer={"A 东岳","B 西岳","C 中岳","D 南岳"},result=3},
[509]={question="上海简称“沪”，其出处与？",answer={"A 港口有关","B 渔具有关"},result=2},
[510]={question="上海东方明珠塔在中国属第一塔，在世界上属？",answer={"A 第一塔","B 第二塔","C 第三塔"},result=3},
[511]={question="上海崇明岛是我国第几大岛？",answer={"A 第一","B 第二","C 第三","D 第四"},result=3},
[512]={question="商人的“商”最早的意思是指？",answer={"A 商朝","B 商量","C 买卖","D 钱币"},result=1},
[513]={question="商老太在金庸看来是个怎样的人物？",answer={"A 喜剧人物","B 悲剧人物","C 闹剧人物","D 不明人物"},result=2},
[514]={question="珊瑚婚是指结婚多少周年？",answer={"A 10","B 25","C 35","D 40"},result=3},
[515]={question="山重水复疑无路，柳暗花明又一村是谁的诗句？",answer={"A 陆游","B 苏轼","C 朱熹","D 欧阳修"},result=1},
[516]={question="山外青山楼外楼在原诗《题临安邸》中的下句是？",answer={"A 西湖歌舞几时休","B 强中自有强中手"},result=1},
[517]={question="山脉常成为气候的分界线，以下四个山脉哪个是暖温带和中温带的分界线？",answer={"A 天山","B 祁连山","C 秦岭","D 大巴山"},result=1},
[518]={question="山东山西的“山”是指：？",answer={"A 太行山","B 五台山","C 武当山","D 祁连山"},result=1},
[519]={question="莎士比亚四大悲剧中哪部又称“王子复仇记”？",answer={"A 《奥赛罗》","B 《哈姆雷特》","C 《麦克白斯》","D 《李尔王》"},result=2},
[520]={question="色彩有冷暖之分，蓝绿属于？",answer={"A 暖色","B 冷色"},result=2},
[521]={question="色布在什么水里浸泡一下再洗就不易褪色？",answer={"A 糖水","B 盐水","C 苏打水","D 烧开的水"},result=2},
[522]={question="三人同日去观花，百友原来共一家，愁人去掉心头肉，终身不挂一根线。(打四字)",answer={"A 花拳秀退","B 才子佳人","C 春夏秋冬","D 冬虫夏00"},result=3},
[523]={question="三千强弩射潮低(打一中国地名)",answer={"A 潮州","B 柳州","C 临江","D 镇江"},result=4},
[524]={question="三明治名字是怎么来的？",answer={"A 根据地名","B 发明这种食品的人名"},result=2},
[525]={question="三过家门而不人是哪一历史人物的故事？",answer={"A 禹","B 舜","C 尧"},result=1},
[526]={question="撒漠 是指：",answer={"A 往四处看","B 武术","C 捡东西","D 荒漠化"},result=1},
[527]={question="如果服用中药，是否可以吃萝卜？",answer={"A 可以","B 不可以"},result=2},
[528]={question="人体最先老化的是哪一部位？",answer={"A 牙齿","B 心脏","C 眼睛","D 大脑"},result=3},
[529]={question="人体最坚硬的部分是？",answer={"A 指甲","B 牙齿","C 骨头","D 眼睛"},result=2},
[530]={question="人体最大的器官是？",answer={"A 脑","B 皮肤","C 肺","D 肠"},result=2},
[531]={question="人体最大的解毒器官是：",answer={"A 胃","B 肾脏","C 肝脏","D 脾"},result=3},
[532]={question="人体中最长的细胞有多长？",answer={"A 10毫米","B 10厘米","C 1米","D 10米"},result=3},
[533]={question="人体消化道中最长的器官是小肠？",answer={"A 不对","B 对"},result=2},
[534]={question="人体生命中最重要的物质是什么？",answer={"A 氨基酸","B 蛋白质","C 维生素","D DNA"},result=2},
[535]={question="人体内数目最多的细胞是什么？",answer={"A 白血球","B 红血球","C 色素细胞","D 腺细胞"},result=2},
[536]={question="人体呼吸系统的组成是：",answer={"A 鼻腔和气管","B 气管和肺","C 气管和支气管","D 呼吸道和肺"},result=4},
[537]={question="人体含水量百分比最高的器官是？",answer={"A 皮肤","B 头发","C 眼球","D 肝脏"},result=3},
[538]={question="人体不能自己产生的是？",answer={"A 荷尔蒙","B 维生素C"},result=2},
[539]={question="人生自古谁无死，留取丹心照汗青的作者是？",answer={"A 文天祥","B 司马迁","C 于谦","D 岳飞"},result=1},
[540]={question="人如果倒立着喝水？",answer={"A 喝不进去","B 水会从鼻中流出","C 和站着喝水效果一样"},result=3},
[541]={question="人们最早是从哪种动物身上得知咖啡的作用的？",answer={"A 驴","B 羊","C 兔子","D 牛"},result=2},
[542]={question="人类是恒温动物，体温总维持在多少摄氏度左右？",answer={"A 35","B 36","C 37","D 38"},result=3},
[543]={question="人口最多的城市是？",answer={"A 巴黎","B 纽约","C 东京"},result=3},
[544]={question="人的牙齿一般共有多少枚？",answer={"A 30","B 32","C 34","D 36"},result=2},
[545]={question="人的五感中那个感觉反应最快？",answer={"A 嗅觉","B 视觉","C 听觉","D 味觉"},result=4},
[546]={question="人的唾液有杀菌作用吗？",answer={"A 有","B 没有"},result=1},
[547]={question="人参的主要产地在？",answer={"A 西藏","B 东北"},result=2},
[548]={question="热狗的名字怎么来的？",answer={"A 最初用狗肉做的","B 形状象狗","C 最初是狗食"},result=2},
[549]={question="热带鱼一般生活在：",answer={"A 咸水中","B 淡水中"},result=2},
[550]={question="群山万壑赴荆门，生长明妃尚有村，“明妃”是指？",answer={"A 文成公主","B 王昭君","C 花木兰"},result=2},
[551]={question="全世界最大的石佛像在？",answer={"A 河南洛阳","B 四川屏山","C 四川江津","D 四川乐山"},result=4},
[552]={question="全国性抗日战争爆发的标志是？",answer={"A 九一八事件","B 七七事件","C 一一八事件","D 一二八事件"},result=2},
[553]={question="屈原是春秋时代哪国人？",answer={"A 楚国","B 鲁国","C 战国"},result=1},
[554]={question="庆卿是对以下哪位剑客的称呼？",answer={"A 王越","B 鲁石公","C 荆柯"},result=3},
[555]={question="请指出“嘎拉哈”是什么东西？",answer={"A 一种食品　","B 动物关节制成的玩具　","C 一种家用器具　","D 一种农用器具"},result=2},
[556]={question="请选出不在东非大裂谷带上的国家：",answer={"A 扎伊尔","B 埃塞俄比亚","C 摩洛哥","D 肯尼亚"},result=3},
[557]={question="请问“马嵬坡”在今日的哪个省境内？",answer={"A 陕西","B 山西"},result=1},
[558]={question="请问“钓游之地”一般指哪里？",answer={"A 故乡","B 客居之地"},result=1},
[559]={question="请问：竹筒烧肉是哪个民族的名菜？",answer={"A 傣族","B 哈尼族","C 土家族"},result=2},
[560]={question="清太宗就是（）。",answer={"A 努尔哈赤","B 皇太极","C 完颜阿骨打","D 忽必烈"},result=2},
[561]={question="清明上河图创作于？",answer={"A 唐朝","B 清朝","C 宋朝","D 明朝"},result=3},
[562]={question="清朝前期全国性的贸易市场是？",answer={"A 扬州","B 苏州","C 北京","D 南京"},result=3},
[563]={question="青蛙除了用肺外还用什么器官呼吸？",answer={"A 肌肉","B 皮肤","C 脾脏","D 肝脏"},result=2},
[564]={question="青龙月神刀多少等级佩戴？",answer={"A 70","B 60","C 55","D 40"},result=2},
[565]={question="琴棋书画中的“棋”指？",answer={"A 象棋","B 围棋","C 古代象棋","D 国际象棋"},result=2},
[566]={question="秦代李斯的代表作品是哪篇？",answer={"A 《吕氏春秋》","B 《谏逐客书》","C 《大风歌》","D 《垓下歌》"},result=2},
[567]={question="秦朝最长的剑最长达到多少厘米？",answer={"A 90厘米","B 85厘米","C 80厘米"},result=1},
[568]={question="亲吻礼源于哪里？",answer={"A 古埃及","B 古罗马","C 古希腊"},result=2},
[569]={question="切过鱼、肉、葱、蒜的菜刀和砧板，用什么擦一下，既可解除腥气，又能防刀生锈？",answer={"A 盐","B 姜"},result=2},
[570]={question="巧克力最早是一种？",answer={"A 点心","B 口粮","C 饮料"},result=3},
[571]={question="强光容易让眼疲劳，我们不宜在强光下看书，对吗？",answer={"A 对","B 不对"},result=1},
[572]={question="牵牛星与织女星哪个体积大？",answer={"A 牵牛星","B 织女星"},result=2},
[573]={question="汽车在什么状态下排放的一氧化碳最多：",answer={"A 高速行驶","B 中速行驶","C 低速行驶","D 停车状态开发动机"},result=4},
[574]={question="汽车在加油站加油时，可以使用手机吗？",answer={"A 可以","B 不可以"},result=2},
[575]={question="十年陈酿怎么获得？",answer={"A 不知道怎么来的","B 马路上拾的","C 找矿工兑换"},result=3},
[576]={question="七月流火指天气？",answer={"A 转暖","B 转凉","C 转阴"},result=2},
[577]={question="七大洲中面积第二的是？",answer={"A 南美洲","B 亚洲","C 非洲","D 大洋洲"},result=3},
[578]={question="扑克牌中的“方块”象征着什么？",answer={"A 憨厚","B 财富","C 诚实","D 安宁"},result=2},
[579]={question="破除满汉不通婚这个祖训的是？",answer={"A 康熙","B 雍正","C 乾隆","D 道光"},result=3},
[580]={question="平面直角坐标系中，右下方为第几象限？",answer={"A 第一象限","B 第二象限","C 第三象限","D 第四象限"},result=4},
[581]={question="乒乓球十九世纪始于那个国家？",answer={"A 中国","B 瑞典","C 法国","D 英国"},result=4},
[582]={question="贫血主要原因是人体内缺少哪一种元素？",answer={"A 钙","B 铁","C 碘","D 氯化纳"},result=2},
[583]={question="皮影戏中的皮影人物一般是用什么材料制成的？",answer={"A 猪皮或马皮","B 胶皮","C 塑料","D 驴皮或牛皮"},result=4},
[584]={question="碰杯的礼仪源自？",answer={"A 英国","B 法国","C 古希腊"},result=3},
[585]={question="烹调时使用哪种器皿会破坏食物营养素？",answer={"A 不锈钢器皿","B 钢锅","C 玻璃器皿","D 搪瓷器皿"},result=2},
[586]={question="农民军失利，李自成被迫向哪里撤退（）。",answer={"A 湖北","B 北京","C 陕西","D 沈阳"},result=3},
[587]={question="鸟的笔画数为？",answer={"A 四画","B 五画","C 六画"},result=2},
[588]={question="你知道世界最高的塔是哪一座？",answer={"A 埃菲尔铁塔","B 多伦多塔","C 东柏林塔","D 莫斯科塔"},result=2},
[589]={question="霓虹灯靠什么发光？",answer={"A 灯丝","B 气体"},result=2},
[590]={question="能为白蚁提供能量的物质是？",answer={"A 纤维素","B 维生素","C 无机盐","D 激素"},result=1},
[591]={question="南岳衡山的最高峰是：",answer={"A 天都峰","B 祝融峰","C 莲花峰"},result=2},
[592]={question="南亚被誉为“宝石之国”的国家是？",answer={"A 斯里兰卡","B 马尔代夫"},result=1},
[593]={question="南极洲最具特色的动物是？",answer={"A 磷虾","B 鲸","C 企鹅","D 海豹"},result=3},
[594]={question="南极冰的平均厚度是多少米？",answer={"A 三千米","B 二千米","C 一千米","D 四千米"},result=2},
[595]={question="内蒙古是世界上最大的羊绒加工地吗？",answer={"A 是","B 不是"},result=1},
[596]={question="哪种维生素可促时钙的吸收？",answer={"A 维生素A","B 维生素B","C 维生素C","D 维生素D"},result=4},
[597]={question="哪种矿石是最重的？",answer={"A 金矿","B 铁矿","C 黑铁矿石"},result=1},
[598]={question="哪种酒除饮用之外还作为日常的调味品？",answer={"A 黄酒","B 香槟酒","C 啤酒"},result=1},
[599]={question="哪种病人不宜饮茶？",answer={"A 心血管疾病","B 急性胃肠炎","C 溃疡病","D 肾衰竭"},result=3},
[600]={question="哪一种米最有黏性？请选择以下三种之一。",answer={"A 籼米","B 糯米","C 粳米"},result=2},
[601]={question="哪一类茶属于发酵茶？",answer={"A 绿茶","B 红茶","C 乌龙茶","D 功夫茶"},result=2},
[602]={question="哪个器官制造了血液？",answer={"A 红血球","B 红骨髓","C 肝脏"},result=2},
[603]={question="目前中国最长的铁路、公路两用桥是南京长江大桥吗？",answer={"A 是","B 不是"},result=1},
[604]={question="目前我国规模最大的商业银行是？",answer={"A 农业银行","B 建设银行","C 中国银行","D 工商银行"},result=4},
[605]={question="目前所有用数码相机拍摄的照片都必须通过彩色打印机打印出来吗？",answer={"A 对","B 不对"},result=2},
[606]={question="目前人类已知的最软石头是什么？",answer={"A 磷灰石","B 石膏","C 方解石","D 滑石"},result=4},
[607]={question="目前观测到的距地球最近的一颗恒星位于：",answer={"A 织女座","B 仙女座","C 半人马座","D 大熊座"},result=3},
[608]={question="木琴属于民族乐器吗？",answer={"A 是","B 不是"},result=2},
[609]={question="怒气丹可持续加几秒怒气？",answer={"A 40","B 10","C 50","D 60"},result=2},
[610]={question="蘑菇属于（）。",answer={"A 藻类植物","B 蕨类植物","C 细菌","D 真菌"},result=4},
[611]={question="明月几时有？把酒问青天。是谁的诗词？",answer={"A 李白","B 白居易","C 苏东坡","D 杜甫"},result=3},
[612]={question="明末农民战争中，大顺政权的建立者是（）。",answer={"A 李自成","B 张献忠","C 黄巢","D 李密"},result=1},
[613]={question="明末农民战争中，称“闯王”的是（）。",answer={"A 李自成","B 张献忠","C 吴三桂","D 戚继光"},result=1},
[614]={question="名言“生命在于运动”是誰说的？",answer={"A 车尔尼夫斯","B 普希金","C 伏尔泰","D 契诃夫"},result=3},
[615]={question="名将伍子胥死于哪柄剑下？",answer={"A 吴钩","B 鱼肠","C 属镂"},result=3},
[616]={question="名剑腾空和以下哪一柄剑是一对？",answer={"A 紫郢","B 画影","C 轩辕"},result=2},
[617]={question="名不正言不顺是哪家的思想？",answer={"A 道家","B 儒家","C 法家","D 名家"},result=2},
[618]={question="棉花的种子可以榨油吗？",answer={"A 可以","B 不可以"},result=1},
[619]={question="蜜蜂中的“蜂王”是？",answer={"A 雌蜂","B 雄蜂"},result=1},
[620]={question="米卢曾经带领几支队伍参加过世界杯？",answer={"A 2","B 3","C 4","D 5"},result=4},
[621]={question="美国又被称为什么？",answer={"A 约翰牛","B 山姆大叔"},result=2},
[622]={question="美国的国花是什么花？",answer={"A 百合","B 玫瑰","C 丁香","D 康乃馨"},result=2},
[623]={question="每年的哪一天为世界粮食日？",answer={"A 2005-5-16","B 2005-10-16"},result=2},
[624]={question="眉毛的生长周期有多久？",answer={"A 一个月","B 两个月","C 三个月"},result=2},
[625]={question="卯时相当于几点？",answer={"A 5－7点","B 7－9点","C 9－11点","D 3－5点"},result=1},
[626]={question="茅盾的“农村三部曲”是？",answer={"A 春蚕秋收残冬","B 雾雨电"},result=1},
[627]={question="猫的眼睛在白天是什么样子的？",answer={"A 圆形","B 线形","C 方形"},result=2},
[628]={question="漫画《三毛流浪记》的作者是？",answer={"A 齐白石","B 丰子凯","C 张乐平","D 张大千"},result=3},
[629]={question="麦哲伦是哪个国家的航海家？",answer={"A 西班牙","B 葡萄牙","C 意大利"},result=2},
[630]={question="骂血人了：",answer={"A 赞美对方是一个有血有肉的人","B 很漂亮","C 脸有血色","D 太狠了，极至"},result=4},
[631]={question="马头琴是我国哪一民族的拉弦乐器？",answer={"A 蒙古族","B 维吾尔族"},result=1},
[632]={question="马头琴是我国哪一民族的拉弦乐器？",answer={"A 汉族","B 彝族","C 蒙古族","D 壮族"},result=3},
[633]={question="马是怎样睡觉的？",answer={"A 站着睡","B 躺着睡","C 坐着睡"},result=1},
[634]={question="冰冻项链是龙皇中的项链不？",answer={"A 是","B 不是"},result=1},
[635]={question="落霞与孤鹜齐飞，秋水共（）。一色出自王勃的《滕王阁序》？",answer={"A 长天","B 长空","C 蓝天"},result=1},
[636]={question="骆驼有双层眼睫毛？",answer={"A 对","B 不对"},result=1},
[637]={question="罗斯福新政的中心措施是？",answer={"A 改革金融业","B 改革农业","C 整顿工业","D 调整商业"},result=3},
[638]={question="罗大佑的作品有：",answer={"A 《恋曲1990》","B 《乡间的小路》","C 《外婆的澎湖湾》","D 《同桌的你》"},result=1},
[639]={question="轮船发出六声短笛，这是表示什么呢？",answer={"A 倒退","B 避让","C 转弯","D 遇险"},result=4},
[640]={question="绿色的花瓣里含有？",answer={"A 叶绿素","B 胡萝卜素","C 叶黄素"},result=1},
[641]={question="陆地水中储量最大的水体是：",answer={"A 地下水","B 江河水","C 冰川水","D 湖泊水"},result=3},
[642]={question="庐外依依杨柳，溪边隐隐木杪(打一中国地名)",answer={"A 芷江","B 麻沙","C 孟津","D 靖安"},result=2},
[643]={question="龙在十二生肖中排行第几？",answer={"A 3","B 4","C 5","D 6"},result=3},
[644]={question="龙门石窟在？",answer={"A 甘肃","B 山西","C 河南"},result=3},
[645]={question="六一居士”是谁的别号？",answer={"A 欧阳修","B 唐伯虎","C 柳亚子","D 老舍"},result=1},
[646]={question="六弦琴是什么乐器的别称？",answer={"A 箏","B 木琴","C 吉他","D 手风琴"},result=3},
[647]={question="流动的楷书是指草书吗？",answer={"A 是","B 不是"},result=2},
[648]={question="刘三姐的故事发生在哪个省？",answer={"A 广西","B 云南"},result=1},
[649]={question="临风舒四翼，映水作双身描写的是？",answer={"A 蜻蜓","B 燕子","C 蝴蝶","D 候鸟"},result=1},
[650]={question="两情若是长久时，又岂在朝朝暮暮语出？",answer={"A 柳永","B 秦观","C 晏殊","D 晏几道"},result=2},
[651]={question="连接几段网线以增加距离时，使用哪件设备最佳？",answer={"A ＢＮＣ接头","B 集线器","C 中继器","D 路由器"},result=3},
[652]={question="历史上称唐玄宗统治前期为？",answer={"A 文景之治","B 开皇之治","C 开元盛世","D 贞观之治"},result=3},
[653]={question="历史剧《屈原》是谁的作品？",answer={"A 胡适","B 郭沫若","C 矛盾","D 郁达夫"},result=2},
[654]={question="李颀的《古从军行》属于什么内容的诗？",answer={"A 田园诗","B 边塞诗","C 山水诗","D 咏物诗"},result=2},
[655]={question="黎族的爱情节是每年农历的哪一天？",answer={"A 2005-3-3","B 2005-6-6"},result=1},
[656]={question="冷水和热水一样重吗？",answer={"A 一样","B 不一样"},result=2},
[657]={question="老舍有一部V描写北京人力车夫生活的长篇小说，是什么？",answer={"A 《骆驼祥子》","B 《茶馆》","C 《春华秋实》","D 《火车集》"},result=1},
[658]={question="老花眼与近视是一回事吗？",answer={"A 是","B 不是"},result=2},
[659]={question="喇叭是对什么乐器的俗称？",answer={"A 号","B 唢呐"},result=2},
[660]={question="拉链的发明最早是在什么上边用的？",answer={"A 包","B 衣服","C 鞋"},result=3},
[661]={question="白月门掌门在那张地图?",answer={"A 黄金城","B 白月门","C 荒野土城"},result=2},
[662]={question="空腹跑步有利健康吗？",answer={"A 有利","B 不利"},result=2},
[663]={question="可以用厚纸做容器来把水烧开吗？",answer={"A 可以","B 不可以"},result=1},
[664]={question="科举制度建立于（）。",answer={"A 南北朝","B 汉朝","C 隋朝","D 唐朝"},result=3},
[665]={question="烤全羊烤的是：",answer={"A 山羊","B 羚羊","C 绵羊"},result=3},
[666]={question="康熙皇帝的年号是？",answer={"A 圣祖","B 高祖","C 高宗","D 太祖"},result=1},
[667]={question="开斋节是斋月的开始吗？",answer={"A 是","B 不是"},result=2},
[668]={question="开车旅游遇到雷雨天气时，人应在哪儿最安全？",answer={"A 汽车里","B 大树下","C 凉亭里"},result=1},
[669]={question="卡塔尔盛产石油？",answer={"A 是的","B 不是"},result=1},
[670]={question="爵是一种典礼时用的酒器，那么爵有几只脚？",answer={"A 一只","B 二只","C 三只","D 四只"},result=3},
[671]={question="距今3500年的匠人学会了铸什么剑？",answer={"A 青铜剑","B 铁剑","C 钢剑"},result=1},
[672]={question="据说，梨园行是因为唐明皇将歌舞伎集中在梨园而得名的是吗？",answer={"A 是","B 不是"},result=1},
[673]={question="举重时运动员为什么搓白粉？",answer={"A 使手变的粗糙","B 吸取手上的汗","C 刺激肌肉","D 保护皮肤"},result=2},
[674]={question="举重比赛的级别是按？",answer={"A 杠铃重量划分","B 运动员体重划分","C 按年龄划分"},result=2},
[675]={question="局域网的英文缩写？",answer={"A LAN","B ADSL","C MAC","D Internet"},result=1},
[676]={question="居住在蒙古与内蒙古地区的民族联合，并自称“蒙古”，起于何时？",answer={"A 耶律亿","B 成吉思汗"},result=2},
[677]={question="就体裁而言，正史都是：",answer={"A 纪传体史书","B 编年体史书","C 纪事本末体史书","D 典志体史书"},result=1},
[678]={question="竞技比赛中的泳姿有几种？",answer={"A 3种","B 4种"},result=2},
[679]={question="景泰蓝的表层用金丝,彩釉装饰,用什么做胎?",answer={"A 铜","B 铁","C 锡"},result=1},
[680]={question="鲸的心脏每小时跳动多少次？",answer={"A 540次","B 600次","C 650次","D 700次"},result=1},
[681]={question="荆轲刺秦王是在何时？",answer={"A 春秋","B 战国","C 秦朝"},result=2},
[682]={question="京剧中“净”这个行当通称为？",answer={"A 老生","B 花脸","C 武生"},result=2},
[683]={question="禁地中有多少种怪物？",answer={"A 7","B 9","C 8"},result=3},
[684]={question="近代史上最伟大的音乐家是？",answer={"A 舒伯特","B 柴可夫斯基","C 约翰施特劳斯","D 贝多芬"},result=4},
[685]={question="劲儿劲儿地：",answer={"A 力大无比","B 皮筋","C 执着，有精神头","D 没完没了"},result=3},
[686]={question="金字塔是古代埃及国王的（）。",answer={"A 陵墓","B 宫殿","C 行宫","D 祭祀殿堂"},result=1},
[687]={question="金庸作品时代背景最早的是哪个？",answer={"A 天龙八部","B 连城决","C 笑傲江湖","D 越女剑"},result=4},
[688]={question="金庸挂印封笔，金盆洗手于多少年？",answer={"A 1970","B 1971","C 1972","D 1973"},result=3},
[689]={question="金庸笔下的“东方不败”是练了以下哪种武功（）。",answer={"A 葵花宝典","B 玉女心经","C 九阴真经","D 九阴白骨掌"},result=1},
[690]={question="金星上会看到“旭日西升”吗？",answer={"A 会","B 不会"},result=1},
[691]={question="结婚50周年被称为金婚，60年是什么婚？",answer={"A 蓝宝石婚","B 红宝石婚","C 钻石婚","D 祖母绿"},result=3},
[692]={question="甲壳虫乐队是来自美国的吗？",answer={"A 是","B 不是"},result=2},
[693]={question="甲骨文史写在哪上面的？",answer={"A 兽皮","B 象牙","C 龟骨","D 恐龙骨"},result=3},
[694]={question="几个人以上共同故意犯罪被称为共同犯罪。",answer={"A 2个","B 3个","C 5个","D 10个"},result=1},
[695]={question="吉它有几根弦？",answer={"A 4根","B 6根","C 7根","D 9根"},result=2},
[696]={question="吉林省抚松县被人们称为是哪种药材之乡？",answer={"A 当归","B 枸杞","C 人参","D 田七"},result=3},
[697]={question="鸡经常啄食地上的小石子，是因为吃石子可以助消化吗？",answer={"A 是","B 不是"},result=1},
[698]={question="鸡蛋里蛋黄和蛋清哪个的脂肪含量高？",answer={"A 蛋黄","B 蛋清"},result=1},
[699]={question="祸起萧墙”的“萧墙”是家中的哪一堵墙？",answer={"A 门墙","B 后院墙","C 东墙","D 内隔墙"},result=1},
[700]={question="火药开始用于军事是在（）。",answer={"A 北宋时","B 唐朝时","C 隋朝时","D 五代时"},result=2},
[701]={question="火腿中有“南腿”之称的是？",answer={"A 苏北火腿","B 金华火腿","C 榕峰火腿"},result=2},
[702]={question="镇魔值卷(礼)一天可使用几次？",answer={"A 5","B 6","C 7"},result=1},
[703]={question="火车机车的发明者是？",answer={"A 瓦特","B 史蒂芬逊"},result=2},
[704]={question="火把节是我国西南地区大部分少数民族共有的古老的民族节日吗？",answer={"A 是","B 不是"},result=1},
[705]={question="“哀其不幸，怒其不争”一语最早见于谁的文章？",answer={"A 鲁迅","B 郭沫若","C 茅盾","D 老舍"},result=1},
[706]={question="黄金分割点是多少？",answer={"A 0.598","B 0.618","C 0.689","D 1.618"},result=2},
[707]={question="黄河壶口瀑布位于陕西与哪个省之间？",answer={"A 宁夏","B 河南","C 山西","D 四川"},result=3},
[708]={question="画龙点睛的传说中被点睛的龙会？",answer={"A 飞走","B 扭动","C 眨眼"},result=1},
[709]={question="户枢不蠹的不蠹是什么意思？",answer={"A 不损耗","B 不生虫"},result=2},
[710]={question="蝴蝶发现花蜜靠？",answer={"A 眼看","B 前足沾","C 嗅觉闻","D 嘴尝"},result=2},
[711]={question="湖北湖南的湖是？",answer={"A 洞庭湖","B 鄱阳湖","C 太湖","D 西湖"},result=1},
[712]={question="红烧菜肴为什么放白糖？",answer={"A 弥补苦味","B 呈色、提香"},result=2},
[713]={question="红娘由来是出自下列哪部古典名剧？",answer={"A 《琵琶记》","B 《西厢记》","C 《长生殿》","D 《桃花扇》"},result=2},
[714]={question="恶魔果实的作用",answer={"A 变成橡胶人","B 成为海贼王"},result=1},
[715]={question="黑龙江的省会是哪？",answer={"A 齐齐哈尔","B 哈尔滨","C 绥化"},result=2},
[716]={question="核电站运用了放射性元素的什么来转化为电能？",answer={"A 裂变","B 聚变","C 衰变","D 化合"},result=1},
[717]={question="和田玉产于？",answer={"A 内蒙古","B 新疆"},result=2},
[718]={question="汉字“廿”是表示：",answer={"A 十","B 二十"},result=2},
[719]={question="汉白玉是什么？",answer={"A 一种名贵的石头","B 一种玉"},result=1},
[720]={question="寒食节是为了纪念谁？",answer={"A 重耳","B 介之推","C 晋文公","D 屈原"},result=2},
[721]={question="含羞草会开花吗？",answer={"A 会","B 不会"},result=1},
[722]={question="海南三亚景点天涯海角巨石上的“天涯”传说是谁的？",answer={"A 吕洞宾","B 苏东坡","C 柳宗元"},result=2},
[723]={question="海内存知己，天涯若比邻是（）的诗句？",answer={"A 白居易","B 李白","C 王勃"},result=3},
[724]={question="海马是马吗？",answer={"A 是","B 不是"},result=2},
[725]={question="哈雪慧星的最早记录是哪国人留下的？",answer={"A 埃及人","B 希腊人","C 中国人","D 波斯人"},result=3},
[726]={question="桂林山水甲天下，什么山水“甲桂林”？",answer={"A 阳朔","B 漓江"},result=1},
[727]={question="广州因何而有“羊城”之名？",answer={"A 人名典故","B 根据五羊的传说","C 羊肉火锅"},result=2},
[728]={question="广东足球彩票发行一年来，共产生多少个百万富翁？",answer={"A 33","B 83","C 123","D 133"},result=3},
[729]={question="广东把馄炖叫做____？",answer={"A 温炖","B 云吞"},result=2},
[730]={question="光经过透明物体，进入另一透明物体时，传播方向会发生偏折，这种现象叫做散射，是吗？",answer={"A 是","B 不是"},result=2},
[731]={question="光合作用吸收的主要是太阳光中的绿光，对吗？",answer={"A 对","B 不对"},result=2},
[732]={question="刮痧是我国民间传统的简易治疗方法，对吗？",answer={"A 对","B 不对"},result=1},
[733]={question="故宫建筑在布局上的主要特点是（）朝（）门？",answer={"A 三　五","B 二　四","C 三　四","D 二　三"},result=1},
[734]={question="故宫博物院原名“紫禁城”，是明清两朝的皇宫，请问那个朝代有14位皇帝在此生活居住？",answer={"A 明朝","B 清朝"},result=1},
[735]={question="太阳药水(大)可恢复多少HP",answer={"A 1000","B 700","C 5200","D 1500"},result=1},
[736]={question="股市里行情中，延续时间相对教长的大跌市被称为？",answer={"A 熊市","B 牛市"},result=1},
[737]={question="古语“朵颐”中的“颐”是指：",answer={"A 耳垂","B 手腕","C 面颊"},result=3},
[738]={question="古书中男子手里常握有“三尺”，请问它指什么？",answer={"A 尺","B 剑","C 扇","D 矛"},result=2},
[739]={question="古时铜钱中有一个方孔是为了？",answer={"A 方便携带","B 方便铸造"},result=2},
[740]={question="古时戒指用来表示？",answer={"A 荣誉","B 富贵","C 禁戒","D 婚否"},result=3},
[741]={question="古诗的体制称为“风雅颂”，其中“颂”是指？",answer={"A 地方民歌","B 王朝正声","C 宗庙乐歌"},result=3},
[742]={question="古人所谓“黄道”是哪种天体运行周年的轨道？",answer={"A 金星","B 月亮","C 太阳","D 地球"},result=3},
[743]={question="古人说的“酢”指的是今天的？",answer={"A 酱油","B 豆油","C 醋","D 酒"},result=3},
[744]={question="古人对“六十岁”年龄的人的称呼是？",answer={"A 而立","B 不惑","C 知天命","D 花甲"},result=4},
[745]={question="古典悲剧《汉宫秋》的作者是谁？",answer={"A 纪君祥","B 关汉卿","C 白朴","D 马致远"},result=4},
[746]={question="古代著名的水利工程都江堰是李冰父子设计的吗？",answer={"A 是","B 不是"},result=1},
[747]={question="古代小说常用“沉鱼落雁,闭月羞花”形容女性之美,其中“闭月”是指？",answer={"A 杨玉环","B 赵飞燕","C 西施","D 貂禅"},result=4},
[748]={question="古代所说的“促织”是指现在的？",answer={"A 蝗虫","B 蟋蟀","C 蝈蝈"},result=2},
[749]={question="古代丝绸之路的开拓者是___________？",answer={"A 唐代的玄奘","B 明代的郑和","C 西汉的司马迁","D 西汉的张骞"},result=4},
[750]={question="古代女子成年行什么礼？",answer={"A 冠礼","B 笄礼"},result=2},
[751]={question="攻打沙城的必须物品，可通过杀死什么怪物获得？",answer={"A 黄天教主","B 雷焰教主","C 魔龙教主"},result=2},
[752]={question="功亏一篑指一件大事只差一点而没能完成，这里的“一篑“指的是？",answer={"A 一天时间","B 一队人马","C 一筐泥土"},result=3},
[753]={question="公元前594年，实行“初税亩”，按亩收税的国家是：",answer={"A 楚国","B 鲁国","C 郑国","D 魏国"},result=2},
[754]={question="公元200年，曹操大败袁绍的战役是（）。",answer={"A 长平之战","B 官渡之战","C 淝水之战","D 赤壁之战"},result=2},
[755]={question="公务员连续两年不称职，应当（）。",answer={"A 辞职","B 降职","C 辞退","D 开除"},result=3},
[756]={question="公民每次献血应控制在多少毫升范围内？",answer={"A 200-400毫升","B 300-500毫升","C 400-500毫升","D 500-600毫升"},result=1},
[757]={question="根据有关规定,职工的试用期最长不得超过？",answer={"A 3个月","B 6个月","C 一年","D 两年"},result=2},
[758]={question="各国北郊里都有一个叫“魔徒“的BOSS吗？",answer={"A 是","B 不是"},result=2},
[759]={question="隔着门缝看人”时，看到的人：",answer={"A 比原来扁了","B 和原来一样"},result=2},
[760]={question="歌棚是哪个民族的习俗？",answer={"A 傣族","B 苗族","C 壮族","D 京族"},result=3},
[761]={question="高祖母是？",answer={"A 曾祖母","B 曾祖的母亲","C 曾祖的祖母"},result=2},
[762]={question="高速缓冲存储器简称为？",answer={"A RAM","B ROM","C CACHE","D CAM"},result=3},
[763]={question="高官骑瘦马的意思是？",answer={"A 窝囊","B 富而不显"},result=2},
[764]={question="钢剑在以下哪个朝代开始普遍使用？",answer={"A 东汉","B 秦初","C 战国末期"},result=3},
[765]={question="感光胶片中的全色片是一种：",answer={"A 黑白感光片","B 彩色感光片"},result=1},
[766]={question="敢于直言，前后向唐太宗进谏200多次的大臣是？",answer={"A 房玄龄","B 杜如晦","C 姚崇","D 魏征"},result=4},
[767]={question="噶鼓：",answer={"A 独特","B 饿了","C 难受","D 一种乐器"},result=1},
[768]={question="符号&的中文意思是？",answer={"A 也","B 但是","C 和"},result=3},
[769]={question="扶桑的铸剑术主要传自中国的哪个时期？",answer={"A 西汉","B 东汉","C 秦"},result=1},
[770]={question="夫妻双方不得相互继承遗产吗？",answer={"A 是","B 不是"},result=2},
[771]={question="佛教传入中国中原的第一座佛庙是？",answer={"A 法门寺","B 白马寺","C 静安寺","D 昭觉寺"},result=2},
[772]={question="疯牛病最早在哪个国家发现的？",answer={"A 英国","B 法国"},result=1},
[773]={question="防风林要达到最好的防风效果，应由：",answer={"A 5—10行树组成","B 10行以上树组成"},result=2},
[774]={question="范进中举的故事出自小说？",answer={"A 《红楼梦》","B 《水浒》","C 《儒林外史》"},result=3},
[775]={question="二椅着：",answer={"A 二把手，副手","B 不男不女","C 二百五","D 双人沙发"},result=2},
[776]={question="二人转是？",answer={"A 东北曲艺","B 陕北曲艺","C 山东曲艺","D 河南曲艺"},result=1},
[777]={question="额前头发的刘海起源与谁有关？",answer={"A 杨玉环","B 上官婉儿"},result=2},
[778]={question="敦煌月牙泉俗名？",answer={"A 药泉","B 清泉"},result=1},
[779]={question="对于最早出现的刀是以下哪种描述是正确的？",answer={"A 直刀","B 弯刀","C 宽刃刀"},result=1},
[780]={question="杜康酒的产地在我国的：",answer={"A 河南","B 山西","C 陕西","D 山东"},result=1},
[781]={question="杜鹃鸟不做窝，她把蛋下到其他鸟的鸟巢里对吗？",answer={"A 对","B 不对"},result=1},
[782]={question="杜甫的诗《江南逢李龟年》中的李龟年是哪个朝代的人？",answer={"A 唐朝","B 宋朝","C 明朝","D 元朝"},result=1},
[783]={question="杜甫的《月夜忆舍弟》中“露从今夜白”，下一句是（）？",answer={"A 有弟皆分散","B 秋边一雁声","C 无家问死生","D 月是故乡明"},result=4},
[784]={question="杜甫的《春夜喜雨》中“晓看红湿处”的下句是（）。",answer={"A 花重锦官城","B 花重锦洲城","C 花重绵阳城"},result=1},
[785]={question="独在异乡为异客，每逢佳节倍思亲是（）。的诗句？",answer={"A 王维","B 王勃","C 王之涣"},result=1},
[786]={question="毒蛇的毒牙一般长在？",answer={"A 上颚","B 下颚"},result=1},
[787]={question="豆科植物可通过根瘤菌固定哪种元素？",answer={"A 氮","B 磷","C 钾","D 氧"},result=1},
[788]={question="冻疮是由于皮肤哪一部分受损而引起的？",answer={"A 毛囊","B 汗腺","C 竖毛肌","D 毛细血管"},result=4},
[789]={question="冬泳时，在下水之前饮用白酒可以御寒吗？",answer={"A 可以","B 不可以"},result=2},
[790]={question="冬天到了，春天还会远吗语出？",answer={"A 鲁迅","B 雪莱","C 华孜"},result=2},
[791]={question="东施效颦出自？",answer={"A 《孟子》","B 《庄子》","C 《论语》","D 《红楼梦》"},result=2},
[792]={question="东三省是哪三省？",answer={"A 京、津、沪","B 湘、鄂、粤","C 黑、吉、辽","D 冀、晋、苏"},result=3},
[793]={question="东汉末年我国的一位杰出的医学家是：",answer={"A 扁鹊","B 华佗","C 李时珍","D 叶天士"},result=2},
[794]={question="东床快婿原本是指？",answer={"A 司马相如","B 赵明诚","C 诸葛亮","D 王羲之"},result=4},
[795]={question="奠定了三国鼎立局面的战争是？",answer={"A 祖逖北伐","B 官渡之战","C 赤壁之战","D 八王之乱"},result=3},
[796]={question="电子计算机发明于哪一年？",answer={"A 1945年","B 1946年","C 1970年"},result=2},
[797]={question="电影名《八千里路云与月》出自谁的词中的名句？",answer={"A 文天祥","B 辛弃疾","C 岳飞"},result=3},
[798]={question="电影《狮子王》用的是三维动画吗？",answer={"A 是","B 不是"},result=2},
[799]={question="电影《刘三姐》是反映-什么民族的生活故事？",answer={"A 壮族","B 黎族","C 瑶族","D 苗族"},result=1},
[800]={question="电台工作人员简称是什么？",answer={"A RC","B DC","C DJ","D RJ"},result=3},
[801]={question="电脑的心脏是什么？",answer={"A cpu","B 硬盘","C 键盘","D 内存"},result=1},
[802]={question="地上、地下文物在我国居于首位的省分别是：",answer={"A 山西、陕西","B 河南、陕西","C 河北、河南","D 山西、河南"},result=1},
[803]={question="当支点到力点的距离小于支点到重点的距离时，杠杆是省力的是吗？",answer={"A 是","B 不是"},result=2},
[804]={question="担担面是哪个省的风味小吃？",answer={"A 四川","B 湖南"},result=1},
[805]={question="大雁塔在哪里？",answer={"A 苏州","B 杭州","C 南京","D 西安"},result=4},
[806]={question="大熊猫又叫？",answer={"A 猫熊","B 竹熊"},result=1},
[807]={question="大熊猫和小熊猫是同一科的吗？",answer={"A 是","B 不是"},result=2},
[808]={question="大象的长牙是它的？",answer={"A 上牙","B 下牙"},result=1},
[809]={question="大气中的水汽主要来源于？",answer={"A 太阳","B 植物蒸腾","C 地球表面水体蒸发","D 大气本身"},result=3},
[810]={question="大夫在我国古代是指？",answer={"A 官职","B 知识分子","C 医生"},result=1},
[811]={question="促进人体胃肠吸收钙的重要物质是：",answer={"A 维生素A","B 维生素B","C 维生素C","D 维生素D"},result=4},
[812]={question="从人物所处的时代角度，选出不同的一项是：",answer={"A 王安石","B 范仲淹","C 欧阳修","D 韩愈"},result=4},
[813]={question="从哪个朝代起剑开始被刀代替？",answer={"A 东汉","B 西晋","C 西汉"},result=3},
[814]={question="春种一粒粟中的粟指？",answer={"A 大米","B 谷子","C 高梁","D 麦子"},result=2},
[815]={question="春眠不觉晓，处处闻啼鸟。夜来风雨声，花落知多少。这首诗的题目是（　）？",answer={"A 春晓","B 冬眠","C 春风","D 春天"},result=1},
[816]={question="春风不度玉门关是谁的诗句？",answer={"A 王之涣","B 杜甫","C 李清照","D 李白"},result=1},
[817]={question="春蚕到死丝方尽，蜡炬成灰泪始干出自（）。的《无题》？",answer={"A 李商隐","B 李贺","C 李清照"},result=1},
[818]={question="创立八旗制度的是？",answer={"A 铁木真","B 努尔哈赤","C 忽必烈","D 皇太极"},result=2},
[819]={question="传统的冰糖葫芦是以什么水果为主要原料？",answer={"A 苹果","B 山楂","C 李子","D 桃子"},result=2},
[820]={question="“百会穴”在：",answer={"A 两眉间","B 头顶正中","C 上唇正中","D 后脑上"},result=2},
[821]={question="传说中的后羿射日时的人类的首领是：",answer={"A 尧","B 舜","C 禹","D 汤"},result=1},
[822]={question="龙皇中转生达到多少级可以开启飞升？",answer={"A 30","B 60","C 40"},result=3},
[823]={question="初出茅庐中的“茅庐”本意是指谁的的住处？",answer={"A 诸葛亮","B 司马迁","C 司马光","D 刘备"},result=1},
[824]={question="出淤泥而不染，濯清涟而不妖是周敦颐称赞（）的名句？",answer={"A 牡丹","B 菊花","C 莲花"},result=3},
[825]={question="赤壁之战中，假装投降以接近曹军的吴国将领是：",answer={"A 黄忠","B 黄巢","C 黄盖","D 姜维"},result=3},
[826]={question="池畔曲径风摆柳，阶前湖中水清清(打一中国地名)",answer={"A 措美","B 汤阴","C 清镇","D 玉树"},result=2},
[827]={question="吃菠萝时为什么加盐水？",answer={"A 减少菠萝酸的酸味","B 减少菠萝碱的苦味","C 减少菠萝酶的刺激"},result=3},
[828]={question="成语“脱颖而出”的‘颖’是什么意思？",answer={"A 优秀","B 稻穗","C 锥尖","D 聪明"},result=3},
[829]={question="称“榨菜”为“榨”是否因腌制过程中榨去水分是一道重要工序？",answer={"A 是","B 不是"},result=1},
[830]={question="车轮滚动一周，所行的路程是求车轮的（）。",answer={"A 直径","B 周长","C 面积"},result=2},
[831]={question="潮汐主要是由什么引力而形成的？",answer={"A 月球","B 太阳"},result=1},
[832]={question="长相思，在长安。络纬秋啼金井栏，微霜凄凄簟色寒。请问此诗的作者是谁？",answer={"A 骆宾王","B 苏颋","C 李白","D 刘希夷"},result=3},
[833]={question="长江的长度是多少？",answer={"A 6300公里","B 6400公里","C 6500公里","D 12000公里"},result=1},
[834]={question="长白山天池略呈：",answer={"A 蚕豆形","B 圆形","C 椭圆形","D 菱形"},result=3},
[835]={question="产于福建的名茶是？",answer={"A 白茶","B 龙井茶","C 黑茶"},result=1},
[836]={question="蟾蜍和青蛙都属于两栖动物，是吗？",answer={"A 是","B 不是"},result=1},
[837]={question="茶叶的含水量高于8%会导致什么后果？",answer={"A 茶叶味道更好","B 发生霉变"},result=2},
[838]={question="曹雪芹写《红楼梦》用了几年的时间？",answer={"A 5年","B 10年","C 15年","D 20年"},result=2},
[839]={question="曹丕既是皇帝又是建安文学的代表人物之一吗？",answer={"A 是","B 不是"},result=1},
[840]={question="采菊东篱下，悠然见南山是陶渊明哪篇作品中的名句（）。",answer={"A 《归园田居》","B 《饮酒》","C 《桃花源记》","D 《归去来兮辞》"},result=2},
[841]={question="布达拉宫是世界上最高的宫殿吗？",answer={"A 是","B 不是"},result=1},
[842]={question="不为五斗米折腰最早是指谁不愿为五斗米折腰？",answer={"A 陶渊明","B 阮籍","C 诸葛亮","D 司马迁"},result=1},
[843]={question="不同的塑料组成有很大差异，但主要原料都是：",answer={"A 环氧化合物","B 合成树脂","C 石蜡","D 聚氯乙烯"},result=2},
[844]={question="不是《诗经》分类方法的是：",answer={"A 风","B 雅","C 赋","D 颂"},result=3},
[845]={question="不会游泳的人在“死海”里会？",answer={"A 沉到水底","B 浮在水面"},result=2},
[846]={question="不动产物权的变动，通常以（）。为公示方法。",answer={"A 交付","B 占有","C 登记","D 合意"},result=4},
[847]={question="蒲公英靠什么传播种子？",answer={"A 风力","B 蜜蜂","C 人工"},result=1},
[848]={question="泊秦淮，烟笼寒水月笼沙，夜泊秦淮近酒家。商女不知亡国恨，隔江犹唱后庭花。作者是：",answer={"A 裴迪","B 王之涣","C 杜牧","D 王建"},result=3},
[849]={question="冰镇啤酒是夏季人们喜爱的饮料。在冬天啤酒能热饮吗？",answer={"A 能","B 不能"},result=1},
[850]={question="冰糖是用白砂糖做的，对不对？",answer={"A 对","B 不对"},result=1},
[851]={question="冰冻的食品也可能有细菌，对吗？",answer={"A 对","B 不对"},result=1},
[852]={question="变脸是哪个剧种的绝活？",answer={"A 粤剧","B 川剧","C 京剧","D 豫剧"},result=2},
[853]={question="碧螺春茶是一种？",answer={"A 红茶","B 绿茶","C 黑茶","D 青茶"},result=4},
[854]={question="被誉为“中国科学史上的里程碑”的书是",answer={"A 十万个为什么","B 中国上下五千年","C 梦溪笔谈"},result=3},
[855]={question="被誉为“药王”的是（）。",answer={"A 张仲景　","B 王叔和","C 神农氏　　","D 孙思邈"},result=4},
[856]={question="被誉为“钢琴之王”的作曲家是：",answer={"A 肖邦","B 勃拉姆斯","C 李斯特","D 约翰·施特劳斯"},result=3},
[857]={question="被唐太宗李世民比作镜子的是谁？",answer={"A 魏征","B 李靖","C 徐茂公","D 刘文静"},result=1},
[858]={question="被褥要常晒，枕头是否也要常晒？",answer={"A 是","B 不是"},result=1},
[859]={question="被定为中国的旅游标志是？",answer={"A 马踏飞燕","B 秦兵马俑"},result=1},
[860]={question="被称为杏月的月份是？",answer={"A 一月","B 二月","C 三月","D 四月"},result=2},
[861]={question="被称为瓷都的北宋城市是：",answer={"A 东京","B 景德镇","C 广州","D 泉州"},result=2},
[862]={question="被称为“英雄树”的是哪种植物？",answer={"A 龙眼","B 木棉","C 富贵菊","D 莲花"},result=2},
[863]={question="被称为“喜剧之王”的是（）。",answer={"A 赵薇","B 周星驰","C 张卫健","D 赵本山"},result=2},
[864]={question="被称为“书圣”的古代书法家是？",answer={"A 欧阳修","B 柳宗元","C 颜真卿","D 王羲之"},result=4},
[865]={question="被称为“诗圣”的唐代诗人为？",answer={"A 白居易","B 杜甫","C 王维"},result=2},
[866]={question="北宋与南宋的关系类似于（）。",answer={"A 西汉和东汉","B 西晋和东晋","C 东魏和西魏","D 唐朝与后唐"},result=2},
[867]={question="北宋时东京保卫战的组织者是（）。",answer={"A 李纲　","B 宗泽","C 岳飞","D 陈东"},result=1},
[868]={question="北宋神宗时期进行改革推行新法的人是谁？",answer={"A 李元昊","B 司马光","C 韩愈","D 王安石"},result=4},
[869]={question="北京在哪一年举办的奥运会？",answer={"A 2006","B 2007","C 2008","D 2009"},result=3},
[870]={question="北京土语“吗愣”是指：",answer={"A 蝴蝶的一种","B 蜻蜓的一种","C 蚂蚁的一种","D 蚊子的一种"},result=2},
[871]={question="北京口语“蝴蝶”的最佳正确读音",answer={"A hǘdié","B hùtiě","C húdié(r)","D hūiě"},result=2},
[872]={question="北京话骂人时经常说“孙子”，请选择“子”的正确读音",answer={"A zǐ","B za","C zèi","D zè"},result=3},
[873]={question="北极星处于天空中的？",answer={"A 大熊星座","B 小熊星座"},result=2},
[874]={question="北极和南极的年平均温度？",answer={"A 一样高","B 南极高","C 北极高"},result=3},
[875]={question="横扫千军可以同时攻击多少敌人",answer={"A 一群","B 5","C 6"},result=1},
[876]={question="横扫千军几级能修练",answer={"A 26","B 28","C 30"},result=2},
[877]={question="板鸭是哪里的特产？",answer={"A 天津","B 南京"},result=2},
[878]={question="百家姓排在第一位的是？",answer={"A 赵","B 钱","C 孙","D 李"},result=1},
[879]={question="霸王别姬的故事最早见于？",answer={"A 《史记》","B 《汉书》"},result=1},
[880]={question="爱国情操的核心是（）。",answer={"A 道德观念","B 强烈的爱国情感","C 法律意识","D 自律意识"},result=2},
[881]={question="阿诗玛是我国云南哪个民族塑造的艺术形象？",answer={"A 彝族","B 瑶族","C 白族","D 苗族"},result=1},
[882]={question="《龙皇传说》怎样购买药品？",answer={"A 元宝商城","B 随身商店","C 以上都可以"},result=3},
[883]={question="2008年奥运会将在哪个城市举行？",answer={"A 巴黎","B 费城","C 莫斯科","D 北京"},result=4},
[884]={question="《资政新篇》是哪一时期的纲领性文件？",answer={"A 太平天国后期","B 洋务运动","C 清末预备立宪","D 戊戌变法"},result=1},
[885]={question="《在那遥远的地方》是？",answer={"A 四川民歌","B 江苏民歌","C 云南民歌","D 青海民歌"},result=4},
[886]={question="《义勇军进行曲》是哪一位作曲家所作的抗日歌曲？",answer={"A 冼星海","B 贺绿汀","C 聂耳","D 麦新"},result=3},
[887]={question="《雪绒花》是哪部影片的插曲？",answer={"A 《音乐之声》","B 《魂断蓝桥》","C 《毕业生》","D 《第凡纳早餐》"},result=1},
[888]={question="《天龙八部》中的乔峰，身世埋在雁门关下。雁门关在：",answer={"A 新疆","B 宁夏","C 山西","D 陕西"},result=3},
[889]={question="《夏意》的作者是？",answer={"A 苏舜钦","B 韩琦","C 韩世宗"},result=2},
[890]={question="《西游记》中的火焰山是今天的？",answer={"A 吐鲁番盆地","B 准格尔盆地","C 柴达木盆地","D 四川盆地"},result=1},
[891]={question="《西游记》中，玉皇大帝除封过孙悟空“齐天大圣”之外，还封过他什么官？",answer={"A 弼马温","B 花果山大王","C 天蓬元帅"},result=1},
[892]={question="《西厢记》的作者是？",answer={"A 白朴","B 关汉卿","C 马致远","D 王实甫"},result=4},
[893]={question="《我的团长我的团》扮演团长的人叫什么？",answer={"A 段奕宏","B 张译"},result=1},
[894]={question="《天演论》是我国近代哪位著名的思想家翻译的？",answer={"A 魏源","B 梁启超","C 严复","D 胡适"},result=3},
[895]={question="《天龙八部》中虚竹娶的是那国的公主？",answer={"A 西夏","B 辽国","C 波斯"},result=1},
[896]={question="《题西林壁》的作者是？",answer={"A 苏轼","B 张献忠","C 司马光"},result=1},
[897]={question="《四库全书》的总纂官是谁？",answer={"A 纪晓岚","B 于敏中","C 乾隆","D 刘庸"},result=1},
[898]={question="《狮子王》和《玩具总动员》都是沃特迪斯尼公司的作品吗？",answer={"A 是","B 不是"},result=1},
[899]={question="《射雕英雄传》中黄蓉的丈夫是谁？",answer={"A 杨康","B 郭靖","C 杨过"},result=2},
[900]={question="《清明上河图》作于？",answer={"A 清代","B 唐代","C 宋代","D 元代"},result=3},
[901]={question="《倾城之恋》、《金锁记》、《传奇》是哪位作家的作品？",answer={"A 琼瑶","B 张爱玲","C 席娟","D 冰心"},result=2},
[902]={question="《霓裳羽衣》是我国哪个朝代的宫廷乐舞？",answer={"A 唐","B 元","C 宋"},result=1},
[903]={question="《洛神赋图》是谁的作品？",answer={"A 王羲之","B 顾恺之","C 吴道子","D 阎立本"},result=2},
[904]={question="《聊斋志异》的作者是谁？",answer={"A 曹雪芹","B 蒲松龄","C 施耐庵","D 笑笑生"},result=2},
[905]={question="《浪客剑心》中绯村剑心脸上竖着的伤疤是谁划上的？",answer={"A 雪代巴","B 雪代缘","C 雪代巴的未婚夫","D 自己"},result=3},
[906]={question="《国际歌》的作词者是？",answer={"A 田汉","B 鲍狄埃","C 狄盖特","D 聂耳"},result=2},
[907]={question="《钢铁是怎样炼成的》作者是谁？",answer={"A 马雅可夫斯基","B 奥斯特洛夫斯基"},result=2},
[908]={question="《村居》的作者是？",answer={"A 张舜民","B 戚继光","C 黄宗羲"},result=1},
[909]={question="《春秋》是按什么记事的？",answer={"A 年","B 国","C 事件"},result=1},
[910]={question="《尝试集》的作者是谁？",answer={"A 鲁迅","B 胡适","C 郭沫若","D 矛盾"},result=2},
[911]={question="《泊船瓜洲》的作者是？",answer={"A 王安石","B 寇准","C 白居易"},result=1},
[912]={question="《本草纲目》的作者是",answer={"A 孙思淼","B 李时珍"},result=2},
[913]={question="“只要有恒心”的下一句是什么？",answer={"A 必定有钱剩","B 铁柱磨成针","C 天下无敌人","D 点石可成金"},result=2},
[914]={question="“执子之手，与子偕老”的出处？",answer={"A 《诗经》","B 《春秋》","C 《楚辞》","D 《孟子》"},result=1},
[915]={question="“知天命”代指什么年纪？",answer={"A 20岁","B 70岁","C 30岁","D 50岁"},result=4},
[916]={question="“运斤成风”比喻技艺神异，手法熟练，这个“斤”字是指：",answer={"A 石墩","B 铜锤","C 斧子","D 铁棍"},result=3},
[917]={question="“元曲四大家”之一的马致远，其代表作是《汉宫秋》对吗？",answer={"A 对","B 不对"},result=1},
[918]={question="“元曲四大家”之一的白朴，其代表作是《梧桐雨》对吗？",answer={"A 对","B 不对"},result=1},
[919]={question="“以血衅金”的铸剑方法最早出自哪个国家？",answer={"A 吴国","B 越国","C 楚国"},result=1},
[920]={question="“一衣带水”的水是指哪条河流？",answer={"A 长江","B 黄河","C 珠江","D 黑龙江"},result=1},
[921]={question="“业精于勤，而荒于嬉”是中国哪位古人提出来的思想？",answer={"A 孔子","B 孟子","C 柳宗元","D 韩愈"},result=4},
[922]={question="“五十步笑百步”出自：",answer={"A 《三国志》","B 《孟子》","C 《晏子春秋》","D 《三国演义》"},result=2},
[923]={question="“我得赶紧找个盆去”。问：是什么意思？",answer={"A 你说的太令人恶心了","B 我准备睡觉了","C 我现在马上要洗菜了","D 我要洗脸了"},result=1},
[924]={question="“问世间，情是何物，直教生死相许”语出：",answer={"A 李莫愁","B 金庸","C 元好问","D 李商隐"},result=3},
[925]={question="“问君能有几多愁”诗句的下句是：",answer={"A 才下眉头，却上心头","B 恰似一江春水向东流","C 剪不断，理还乱","D 却道天凉好个秋"},result=2},
[926]={question="“魏晋风度”的主要载体是《世说新语》吗？",answer={"A 是","B 不是"},result=1},
[927]={question="“屠龙刀”的标准属性为？",answer={"A 攻击5-30","B 攻击5-40","C 攻击5-35"},result=3},
[928]={question="“甜城”是指我国的哪个城市？",answer={"A 攀枝花","B 内江","C 洛阳","D 柳州"},result=2},
[929]={question="“天长地久有时尽，此恨绵绵无绝期”选自哪里？",answer={"A 长恨歌","B 正气歌","C 大风歌","D 晚晴"},result=1},
[930]={question="“他呀，谁也不吝”！问：这是形容那个人？",answer={"A 不管是谁都不放在眼里","B 对谁都很大方","C 谁都不认识","D 是个“自来熟儿”。"},result=1},
[931]={question="“生命诚可贵，爱情价更高”作者是哪国人？",answer={"A 匈牙利","B 俄国","C 法国","D 中国"},result=1},
[932]={question="“三北”防护林体系不包括的省区有：",answer={"A 黑龙江","B 山西","C 河南","D 青海"},result=3},
[933]={question="“孺子牛”原指：",answer={"A 小牛","B 小孩牵的牛","C 小孩牵人假扮的牛","D 小孩牵的小牛"},result=3},
[934]={question="“人生能有几回搏”这句名言最初出自哪位运动员？",answer={"A 容国团","B 许海峰","C 郎平","D 聂卫平"},result=1},
[935]={question="“悄悄地挥一挥手，不带走一片云彩”的是诗人：",answer={"A 徐志摩","B 舒婷","C 席慕容","D 北岛"},result=1},
[936]={question="“贫不及素”中的“素”指的是？",answer={"A 豆腐","B 羊皮","C 白米","D 白色的帛"},result=4},
[937]={question="“明月几时有？把酒问青天。”是谁的诗词？",answer={"A 李白","B 白居易","C 苏东坡","D 杜甫"},result=3},
[938]={question="“民告官”是以下哪种法律行为的俗称？",answer={"A 刑事诉讼","B 民事诉讼","C 行政诉讼","D 劳动仲裁"},result=3},
[939]={question="“黄果树瀑布”位于哪个省？",answer={"A 湖南","B 贵州","C 四川","D 江西"},result=2},
[940]={question="“户枢不蠹”的“不蠹”是什么意思？",answer={"A 不打扫","B 不来往","C 不长虫"},result=3},
[941]={question="“何以解忧，惟有杜康”中的“杜康”是什么的代称？",answer={"A 乐曲","B 美人","C 谋士","D 酒"},result=4},
[942]={question="“何处招魂，香草还生三户地；当年呵壁，湘流应识九歌心”，这幅对联说的是：",answer={"A 贾谊","B 诸葛亮","C 屈原","D 文天祥"},result=3},
[943]={question="“戈能”是指",answer={"A 垃圾","B 一种能量","C 一种粥","D 没能耐"},result=1},
[944]={question="“浮溜浮溜儿的”：",answer={"A 水面上","B 满了","C 降水","D 大风"},result=2},
[945]={question="“飞流直下三千尺，疑是银河落九天”。出自《望庐山瀑布水二首》其作者是（）。",answer={"A 李白","B 金庸","C 琼瑶","D 王晶"},result=1},
[946]={question="“东施效颦”出自：",answer={"A 《孟子》","B 《庄子》","C 《论语》","D 《红楼梦》"},result=2},
[947]={question="“东床快婿”原本是指谁：",answer={"A 司马相如","B 刘邦","C 诸葛亮","D 王羲之"},result=4},
[948]={question="“丁把儿”：",answer={"A 菜刀","B 铁钉","C 总是"},result=3},
[949]={question="“得道者多助，失道者寡助”出自哪一本古代典籍？",answer={"A 《左传》","B 《战国策》","C 《孟子》","D 《庄子》"},result=3},
[950]={question="“大马哈鱼”在我国原产哪里？",answer={"A 长江流域","B 黄河流域","C 黑龙江流域","D 珠江流域"},result=3},
[951]={question="“大拉乎吃的”",answer={"A 很多","B 没有啦","C 不循规矩和礼节，盲目作大","D 数不过来"},result=3},
[952]={question="“垂帘听政”始于何时？",answer={"A 宋朝","B 元朝","C 唐朝","D 清朝"},result=3},
[953]={question="“初唐四杰”中有：",answer={"A 王绩","B 王勃","C 王维","D 王之焕"},result=2},
[954]={question="“草圣”是指那位书法家？",answer={"A 张旭","B 王羲之","C 张芝","D 怀素"},result=1},
[955]={question="“变脸”是哪个剧种的绝活？",answer={"A 京剧","B 豫剧","C 粤剧","D 川剧"},result=4},
[956]={question="“碧云天，黄叶地，北雁南飞”语出：",answer={"A 《墙头马上》","B 《窦娥冤》","C 《西厢记》","D 《牡丹亭》"},result=3},
[957]={question="“百岁神医”孙思邈是世界上第一个发明导尿术的人，您知道他是用什么导尿的吗？",answer={"A 竹签","B 苇管","C 葱管","D 秫秸"},result=3},
[958]={question="故宫博物院原名“紫禁城”，是明清两朝的皇宫，请问那个朝代有14位皇帝在此生活居住？",answer={"A：明朝","B：清朝"},result=1},
}
